### ISSUE TITLE
Error in pm2 logs and all modules on default page 

### ISSUE THREAD

**Issue by Ax-LED** [edward-shen/MMM-pages#11]
**Describe the bug**
After updating the module the single pages (in my case 4) dont exist, instead the modules are all show on default page (page one).

**To Reproduce**
Update the module and restart mm

**Expected behavior**

**Screenshots**

**Please fill out the following information;**
 - Node version: 9.11.2
 - Have you updated to the latest MagicMirror core? no
 - Please post the relevant part of your config file here:
```json
{
			module: 'MMM-pages',
			config: {
					modules:
						[["MMM-MyCalendar", "MMM-GoogleMapsTraffic"],//Seite A
						 ["MagicMirror-FootballLeagues", "MMM-PublicTransportHafas"],//Seite T
						 ["MMM-WeeklySchedule"],//Seite L
						 ["updatenotification", "MMM-SystemStats"]],//Seite Status
					excludes: ["alert", "clock", 'MMM-forecast-io', "newsfeed", "MMM-page-indicator","MMM-Navigate","MMM-Podcast","MMM-WatchDog","MMM-ModuleScheduler","MMM-PIR-Sensor","MMM-Remote-Control"],
					}
		},
```
 - Please post any errors you see about MMM-Pages in the console (Hit F12 > Console when the Magic Mirror window is focused), or write **None** if there aren't any:
PM2 logs
/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       | ERROR! Could not validate main module js file.
0|mm       | /home/pi/MagicMirror/modules/MMM-pages/MMM-pages.js:162
0|mm       |       )); this.config.animationTime / 2);
0|mm       |       ^
0|mm       | SyntaxError: Unexpected token )

```
```
Greetings AxLED

**Comment by edward-shen** [comment]
Hmm, that's strange, because the syntax is correct at that location.

Can you do me a favorite and delete the module folder and reclone it from github? It won't delete any of your settings, but it might fix the issue.

**Comment by edward-shen** [comment]
Additionally, please try updating magic mirror core if the above doesn't solve the issue. You can do so by doing `git pull && npm install` while inside the magic mirror folder.

**Comment by Ax-LED** [comment]
Hi edward-shen,
thanks for your reply, deleting the MMM-pages folder and git clone from your repository didnt help.
Same error: 
```
 ERROR! Could not validate main module js file.
0|mm       | /home/pi/MagicMirror/modules/MMM-pages/MMM-pages.js:162
0|mm       |       )), this.config.animationTime / 2);
0|mm       |       ^
```

For your second suggestion right now i dont want to update to mm 2.4.1 because of the CPU issue and the kms fake driver (which brings new problems). I am staying with MM 2.3.1.

AxLED

**Comment by edward-shen** [comment]
I can't seem to replicate the behavior: I have a v2.3.1 working perfectly on my test instance with this module. 

For now, try reverting to an older version. Go to the MMM-pages folder and type this: `git reset --hard 92c4`. Does the problem still persist?

**Comment by GeckospotNixie** [comment]
Hi edward
I have this same issue and have had it for about 2 weeks.
Check out [https://forum.magicmirror.builders/topic/8624/mmm-pages-not-able-to-get-it-to-be-consistent-all-modules-on-page-one](url)
I'm running Stretch and MM 2.4.1
I have no errors in pm2 file but there are something in the console see attached files.
[Console Pages Error.log](https://github.com/edward-shen/MMM-pages/files/2333813/Console.Pages.Error.log)
[MagicMirror-error.log](https://github.com/edward-shen/MMM-pages/files/2333815/MagicMirror-error.log)
[MagicMirror-out.log](https://github.com/edward-shen/MMM-pages/files/2333816/MagicMirror-out.log)
I hope this helps!

**Comment by edward-shen** [comment]
Hey @GeckospotNixie, I'm really sorry that you've been having this problem for multiple weeks!

I suggested reverting to an earlier version for @Ax-LED because he's using an older version of MM, which I currently suspect that the older version of MM does not support a JS feature that a newer version of MM has. 

As for your issue, it might be related to the issue posted at the end of #9.

Honestly, I have no idea why this behavior occurs with your setup, the log files you provided show no indicator that MMM-pages is failing. I'll try to do some debugging and get back to both of you.

**Comment by edward-shen** [comment]
@Ax-LED You said you were able to fix it after reverting to an older version? Can you please go into the MMM-pages directory and tell me the first 5 or so characters you see after running `git rev-parse HEAD`?

**Comment by edward-shen** [comment]
@GeckospotNixie Could you try disabling MMM-NOAA and tell me if the issue persists?

**Comment by GeckospotNixie** [comment]
Edward
Thank you for the reply!
So I'm new to MagicMirror and I guess new to Linux and Raspberry Pi.
Well I thought I knew something but this project has me thinking I'm a noob.
Ok I have done what you’re asking a number of times.
This is the strangest thing if I strip the config file so it only has the standard modules and restart I can get it to work.
So then I build up the config file with all the modules on the pages I like and it will work and I can even reboot and it will work.
But see as this is a work in progress I shut down the Pi at night.
Then when I boot it up the next day all modules are on the first page.
And I have not found out why or how to solve this.
This is the history working on your request now.

**Comment by GeckospotNixie** [comment]
Edward
Last night when I said it was working it really was not.
It would switch between pages 2 and 3 and not display page 1.
NOAA was on page 2.

This morning I again had the issue all items on the first page and not switching.
I'm not sure but I think your right the NOAA module is giving issues in this setup.
So I got a console log first thing. 'Pages Error 08-30-18 09_05.log'

I changed the config file removing NOAA and it all started working. 
Console log 'Pages  Error 08-30-18 09_22.log'

Here is my config file now
[Pages  Error 08-30-18 09_05.log](https://github.com/edward-shen/MMM-pages/files/2336367/Pages.Error.08-30-18.09_05.log)
[Pages  Error 08-30-18 09_22.log](https://github.com/edward-shen/MMM-pages/files/2336369/Pages.Error.08-30-18.09_22.log)

[public_config.js.log](https://github.com/edward-shen/MMM-pages/files/2336371/public_config.js.log)

Hope this all helps.
GeckospotNixie

**Comment by Ax-LED** [comment]
Hi Edward,
here is the response of `git rev-parse HEAD` (my old, working version):
```
pi@raspberrypi:~/MagicMirror/modules/MMM-pages $ git rev-parse HEAD
edc1e08e65174c69db188894cd58e6e078f42716
```
AxLED

**Comment by Ax-LED** [comment]
Hi Edward,
i have further details, the error and the behavior with all modules on default site only occurs on the display connected to pi directly. If i open MM from a webbrowser in LAN the setup of my pages is perfect. 
Maybe this helps to find the error. Could it be, that electron does different interpreting vs. firefox browser on a pc?
AxLED

**Comment by Ax-LED** [comment]
Hi Edward,
i guess i found the reason, it is in the `setTimeout` code.
If i change the code in MMM-pages.js (latest version) from
```
setTimeout(() => MM.getModules()
      .withClass(this.config.modules[self.curPage])
      .enumerate(module => module.show(
        self.config.animationTime / 2,
        { lockString: self.identifier },
      )), this.config.animationTime / 2);
```
to the spelling of your old (and working) version:
 ```
setTimeout(() => {
        MM.getModules()
          .withClass(self.config.modules[self.curPage])
          .enumerate((module) => {
            module.show(
              self.config.animationTime / 2,
              { lockString: self.identifier }
            );
          });
      }, this.config.animationTime / 2);
```
it works (on Display direct connected to pi and LAN via browser).
AxLED

**Comment by edward-shen** [comment]
Sorry for the delay, but I've made a push now that implements your fix.

Let me know if that helps.

**Comment by Ax-LED** [comment]
Hi Edward,
unfortunatelly the fix doesnt work, same behavior like on my first post in this issue.
```
 /home/pi/MagicMirror/modules/MMM-pages/MMM-pages.js:156
0|mm       |       )), this.config.animationTime / 2);
0|mm       |       ^
0|mm       | SyntaxError: Unexpected token )
```
AxLED

**Comment by Olli6** [comment]
> Hi Edward,
> i guess i found the reason, it is in the `setTimeout` code.
> If i change the code in MMM-pages.js (latest version) from
> 
> ```
> setTimeout(() => MM.getModules()
>       .withClass(this.config.modules[self.curPage])
>       .enumerate(module => module.show(
>         self.config.animationTime / 2,
>         { lockString: self.identifier },
>       )), this.config.animationTime / 2);
> ```
> to the spelling of your old (and working) version:
> 
> ```
> setTimeout(() => {
>        MM.getModules()
>          .withClass(self.config.modules[self.curPage])
>          .enumerate((module) => {
>            module.show(
>              self.config.animationTime / 2,
>              { lockString: self.identifier }
>            );
>          });
>      }, this.config.animationTime / 2);
> ```
> it works (on Display direct connected to pi and LAN via browser).
> AxLED

Thank you Ax-LED! I had the same problem but this fix solved it. 👍

**Comment by edward-shen** [comment]
@Olli6 Hey!

Honestly I'm still pretty bugged about this change. Can you also do me a favor and provide your node version and magic mirror version?

Are you using the newest version?

**Comment by Olli6** [comment]
Hi! Sorry for the delay in my response. As soon as I find out how to figure out my MM version and node version I will tell you - in other words - if you can tell me how to do it I can check it for you! Sorry, I am pretty noob at this.

**Comment by edward-shen** [comment]
Please go into a terminal on your Pi and change the directory to the location where MagicMirror resides.

Then, run the following commands:
```
cat package.json | grep "version"
node --version
```

Thanks!

**Comment by Olli6** [comment]
MM version 2.2.2 and node v6.12.2

**Comment by edward-shen** [comment]
Thanks for the fast reply!

I believe this issue no longer exists on newer versions of Magic Mirror and nodejs. If you have nothing holding you back from updating (e.g. some weird module that requires an older version of magic mirror), please consider updating!

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install -y nodejs
git pull && npm install
```

**Comment by hco125** [comment]
same problem,

see link:
https://github.com/edward-shen/MMM-pages/issues/4#issuecomment-450463632

**Comment by BrunoZumba** [comment]
> Hi Edward,
> i guess i found the reason, it is in the `setTimeout` code.
> If i change the code in MMM-pages.js (latest version) from
> 
> ```
> setTimeout(() => MM.getModules()
>       .withClass(this.config.modules[self.curPage])
>       .enumerate(module => module.show(
>         self.config.animationTime / 2,
>         { lockString: self.identifier },
>       )), this.config.animationTime / 2);
> ```
> to the spelling of your old (and working) version:
> 
> ```
> setTimeout(() => {
>        MM.getModules()
>          .withClass(self.config.modules[self.curPage])
>          .enumerate((module) => {
>            module.show(
>              self.config.animationTime / 2,
>              { lockString: self.identifier }
>            );
>          });
>      }, this.config.animationTime / 2);
> ```
> it works (on Display direct connected to pi and LAN via browser).
> AxLED

I got the same error here and Ax-LED's solution was what worked for me.

Here are my "versions":
~/MagicMirror$ **cat package.json | grep "version"**
  "version": "2.6.0",
~/MagicMirror$ **node --version**
v9.11.2

Just for the record in case anyone stumble upon this :)

And Edward, thanks for the great module!!!!

**Comment by edward-shen** [comment]
Thanks for filing a bug report. I'm surprised that the issue still exists in newer versions of MM, so I've just implemented the fix suggested by @Ax-LED, and properly credited him in the git commit.

Please let me know if the issue persists with the newest update of MMM-pages.

**Comment by edward-shen** [comment]
I'm going to close this issue since I've implemented the fix, but please feel free to comment on this issue again if the problem persists.

**Comment by ChrisGilson** [comment]
Feb 2020 and have found a module that doesn't work with MMM-pages.... MMM-GoogleTasks. Which module would this be an issue with?

**Comment by edward-shen** [comment]
See jgauth/MMM-GoogleTasks#5, it's a problem with MMM-GoogleTasks.

**Comment by ChrisGilson** [comment]
I guess then give its been 2 years this isn't going to get fixed.

**Comment by edward-shen** [comment]
From that post it looks like there's a fork ([jayked/MMM-GoogleTasks](https://github.com/jayked/MMM-GoogleTasks)) that supposedly fixes it. Caveat emptor, haven't tried it myself.

**Comment by ChrisGilson** [comment]
OK great thanks. Just installed this version and it works :)

**Comment by edward-shen** [comment]
Glad to be of help.
