### ISSUE TITLE
doesn't work with 'MMM-Netatmo-Thermostat'

### ISSUE THREAD

**Issue by smotx** [edward-shen/MMM-pages#12]
Hi,

If i add 'MMM-Netatmo-Thermostat' to config.js, 'MMM-Pages' no longer changes page.

Specifically, I see 'Indicator' changed the page, but the display stays on the page '1', nothing changes on the other pages.

No error on 'npm start'

Node version : 9.11.2

**Comment by smotx** [comment]
`var config = 
{
	address: "0.0.0.0",
	port: 8080,
	electronOptions: {
		
	},
	ipWhitelist: [],
	language: "fr",
	modules: [
		{
			module: "MMM-pages",
			config: {
				modules:
				[
				//page Principale
				["MMM-CalendarExt", "internet-monitor", "MMM-Hue", "MMM-FreeBox-Monitor", "MMM-TPLink", "MMM-Tools", "MMM-MyCommute", "MMM-xiaomi", "newsfeed", "MMM-Netatmo-Thermostat"],
				//Listes & autres
				["MMM-Wunderlist-Enhanced"],
				],
			excludes: ["clock", "MMM-page-indicator", "currentweather","weatherforecast", "alert", "updatenotification", "MMM-Remote-Control"],
			rotationTime: 18000
			}
		},
		{
			module: "MMM-page-indicator",
			position: "bottom_bar",
			config: {
				pages: 2,
			}
		},
	   	{
			module: "alert",
			config: {
				
			}
		},
		{
			module: "updatenotification",
			position: "bottom_bar",
			config: {
				
			}
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				
			}
		},
		{
		module: 'MMM-MyCommute',
		position: 'top_left',
		header: 'Trajets : Maison < > xxxx',
		config: {
			apikey: 'xxxxx',
			origin: 'xxxx, france',
			startTime: '00:00',
			endTime: '23:59',
			hideDays: [],
			destinations: [
				{
				destination: 'xxxx, france',
				label: '> xxx',
				mode: 'driving',
				alternatives: true,
				color: '#82E5AA'
				},
			]
		}
		},
		{
		module: 'MMM-MyCommute',
		position: 'top_left',
		config: {
			apikey: 'xxxx',
			origin: 'xxxx, france',
			startTime: '00:00',
			endTime: '23:59',
			hideDays: [],
			destinations: [
				{
				destination: 'xxxx, france',
				label: '> Home',
				mode: 'driving',
				alternatives: true,
				color: '#82E5AA'
				},
			]
		}
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "xxxx",
				locationID: "",
				appid: "xxxx",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
					}
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			config: {
				location: "Bruz",
				locationID: "",
				appid: "xxxx",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
				}
			}
		},
{
			module: "MMM-Netatmo-Thermostat",
			header: 'Température Netatmo',
			position: "top_center",
			config: {
				clientId: "xxx",
				clientSecret: "xxx",
				refreshToken: "xxxx",
				updateInterval: 600000,
				color: {
				heating: "orange",
				cooling: "purple",
				off: "grey"
			}
		}
		},
		{
		module: 'MMM-xiaomi',
		position: 'top_center',
		header: 'Températures/Humidité des pièces',  // This is optional
		config: {
			gatewayIP: '192.168.1.154',
			gatewayToken: 'xxxx',
			showWindow: true,
			showVentilation: true,
			showLights: false,
			audioNotifications: false,
			rooms:  [
				{
					name: 'Salon',
					sortOrder: 10,
					devices : ['158d0001a1fa8f']
				},
				{
					name: 'Chambre',
					sortOrder: 20,
					devices : ['158d0001a1faa0', '158d0001ab1f9c']
				},
				{
					name: 'Cuisine',
					sortOrder: 10,
					devices : ['158d000171dfeb', '158d0001a65ef5']
				},
				{
					name: 'Dressing',
					sortOrder: 10,
					devices : ['158d0001d6debe']
				},
				{
					name: 'Couloir',
					sortOrder: 10,
					devices : ['158d0001d6f7e3']
				},
			]
			}
		},
		{
			module: "newsfeed",
			position: "upper_third",
			config: {
				feeds: [
					{
						title: "France Info Monde",
						url: "https://www.francetvinfo.fr/monde.rss"
					}
				],
				startTags: [
					
				],
				endTags: [
					
				],
				prohibitedWords: [
					
				]
			}
		},
		{
			module: 'MMM-CalendarExt',
			position: "middle_center", //anywhere. It is not related to real position of view
			config: { // Read below
			  system: {
				show: ['daily', 'monthly'],
				locale: 'fr-FR',
				fullDayEventLocalize: 1,
				redrawInterval: 60000, //minimum 60000
			  },
			  defaultView: {
				position: 'middle_center',
			  dateFormat: "D MMM",
			  fullDayEventDateFormat: "D MMM",
			  oneLineEvent:0,
			  overflowRolling: 1,
			  overflowHeight: 400,
			  overflowDuration: 5,
			  weekdayFormat: 'dddd',
			  },
			  calendars: [
				{
				name: 'Médicale', 
				styleName:"style22",
				symbol:"medikit@fa",
				url: "https://calendar.google.comxxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style21",
				symbol:"high_heel@em",
				url: "https://calendar.google.com/calendar/ical/xxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style8",
				symbol:"male-office-worker@em",
				url: "https://calendar.google.com/xxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style11",
				symbol:"male@fa",
				url: "https://calendar.google.com/xxxx/basic.ics"
				}
			  ]
			}
		},
		{
		module: 'MMM-Wunderlist-Enhanced',
		position: 'middle_center',	// This can be any of the regions. Best results in left or right regions.
		header: '', // This is optional
		config: {
			// See 'Configuration options' for more information.
                        accessToken: "xxxx",  //example token
                        clientID: "xxxx",   //example clientID
                        lists: [xxxx]			
		}
		},
		{
			module: "internet-monitor",
			position: "bottom_left",
			header: "Internet Monitor",
			config: {
				type: "",
				maxTime: 20000,
				updateInterval: 1500000,
				verbose: false,
				displayStrength: true,
				displaySpeed: true,
				strengthIconSize: 20,
				maxGaugeScale: 35,
				wifiSymbol:{
					size: 50,
					fullColor: '#3afc25',
					almostColor: '#ffff0c',
					halfColor: '#ff8c00',
					noneColor: '#ff1111'
				}
			}
		},
		{
			module: "MMM-FreeBox-Monitor",
			position: "bottom_left",
			header: "FreeBox Monitor",
			config: {
				mirrorName: "My Magic Mirror",
				ip: "http://88.179.65.106:46575"
				}
		},
		{
			module: 'MMM-Tools',
			position: 'bottom_left',
			header: 'Magic Mirror Status',
			config: {
				device : "RPI", // "RPI" is also available
				refresh_interval_ms : 10000,
				warning_interval_ms : 1000 * 60 * 5,
				enable_warning : true,
				warning : {
				CPU_TEMPERATURE : 70,
				GPU_TEMPERATURE : 65,
				CPU_USAGE : 75,
				STORAGE_USED_PERCENT : 80,
				MEMORY_USED_PERCENT : 80
				}
			}
		},
		{
			module: 'MMM-Hue',
		    position: 'bottom_right',
			header: 'Lumières',
		    config:{
               bridgeip: "192.168.1.253",
		       userid: "xxxx"
				}
		},
		{
			module: 'MMM-TPLink',
			position: 'bottom_right',
			header: 'Prises connectées',
			config: {
			}
		},
		{
			module: "MMM-Remote-Control",
			position: "bottom_bar",
			config: {
				
			}
		},
		],
	paths: {
		modules: "modules",
		vendor: "vendor"
	}
}

if (typeof module !== 'undefined') {module.exports = config;}
`

**Comment by smotx** [comment]
{
	address: "0.0.0.0",
	port: 8080,
	electronOptions: {
		
	},
	ipWhitelist: [],
	language: "fr",
	modules: [
		{
			module: "MMM-pages",
			config: {
				modules:
				[
				//page Principale
				["MMM-CalendarExt", "internet-monitor", "MMM-Hue", "MMM-FreeBox-Monitor", "MMM-TPLink", "MMM-Tools", "MMM-MyCommute", "MMM-xiaomi", "newsfeed", "MMM-Netatmo-Thermostat"],
				//Listes & autres
				["MMM-Wunderlist-Enhanced"],
				],
			excludes: ["clock", "MMM-page-indicator", "currentweather","weatherforecast", "alert", "updatenotification", "MMM-Remote-Control"],
			rotationTime: 18000
			}
		},
		{
			module: "MMM-page-indicator",
			position: "bottom_bar",
			config: {
				pages: 2,
			}
		},
	   	{
			module: "alert",
			config: {
				
			}
		},
		{
			module: "updatenotification",
			position: "bottom_bar",
			config: {
				
			}
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				
			}
		},
		{
		module: 'MMM-MyCommute',
		position: 'top_left',
		header: 'Trajets : Maison < > xxxx',
		config: {
			apikey: 'xxxxx',
			origin: 'xxxx, france',
			startTime: '00:00',
			endTime: '23:59',
			hideDays: [],
			destinations: [
				{
				destination: 'xxxx, france',
				label: '> xxx',
				mode: 'driving',
				alternatives: true,
				color: '#82E5AA'
				},
			]
		}
		},
		{
		module: 'MMM-MyCommute',
		position: 'top_left',
		config: {
			apikey: 'xxxx',
			origin: 'xxxx, france',
			startTime: '00:00',
			endTime: '23:59',
			hideDays: [],bug
			destinations: [
				{
				destination: 'xxxx, france',
				label: '> Home',
				mode: 'driving',
				alternatives: true,
				color: '#82E5AA'
				},
			]
		}
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "xxxx",
				locationID: "",
				appid: "xxxx",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
					}
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			config: {
				location: "xxx",
				locationID: "",
				appid: "xxxx",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
				}
			}
		},
{
			module: "MMM-Netatmo-Thermostat",
			header: 'Température Netatmo',
			position: "top_center",
			config: {
				clientId: "xxx",
				clientSecret: "xxx",
				refreshToken: "xxxx",
				updateInterval: 600000,
				color: {
				heating: "orange",
				cooling: "purple",
				off: "grey"
			}
		}
		},
		{
		module: 'MMM-xiaomi',
		position: 'top_center',
		header: 'Températures/Humidité des pièces',  // This is optional
		config: {
			gatewayIP: '192.168.1.154',
			gatewayToken: 'xxxx',
			showWindow: true,
			showVentilation: true,
			showLights: false,
			audioNotifications: false,
			rooms:  [
				{
					name: 'Salon',
					sortOrder: 10,
					devices : ['158d0001a1f']
				},
				{
					name: 'Chambre',
					sortOrder: 20,
					devices : ['158d0001faa0', '158001ab1']
				},
				{
					name: 'Cuisine',
					sortOrder: 10,
					devices : ['15d00171d', '158d0001a6']
				},
				{
					name: 'Dressing',
					sortOrder: 10,
					devices : ['158d0001d6d']
				},
				{
					name: 'Couloir',
					sortOrder: 10,
					devices : ['158d0001d6']
				},
			]
			}
		},
		{
			module: "newsfeed",
			position: "upper_third",
			config: {
				feeds: [
					{
						title: "France Info Monde",
						url: "https://www.francetvinfo.fr/monde.rss"
					}
				],
				startTags: [
					
				],
				endTags: [
					
				],
				prohibitedWords: [
					
				]
			}
		},
		{
			module: 'MMM-CalendarExt',
			position: "middle_center", //anywhere. It is not related to real position of view
			config: { // Read below
			  system: {
				show: ['daily', 'monthly'],
				locale: 'fr-FR',
				fullDayEventLocalize: 1,
				redrawInterval: 60000, //minimum 60000
			  },
			  defaultView: {
				position: 'middle_center',
			  dateFormat: "D MMM",
			  fullDayEventDateFormat: "D MMM",
			  oneLineEvent:0,
			  overflowRolling: 1,
			  overflowHeight: 400,
			  overflowDuration: 5,
			  weekdayFormat: 'dddd',
			  },
			  calendars: [
				{
				name: 'Médicale', 
				styleName:"style22",
				symbol:"medikit@fa",
				url: "https://calendar.google.comxxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style21",
				symbol:"high_heel@em",
				url: "https://calendar.google.com/calendar/ical/xxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style8",
				symbol:"male-office-worker@em",
				url: "https://calendar.google.com/xxxx/basic.ics"
				},
				{
				name: 'xxxx', 
				styleName:"style11",
				symbol:"male@fa",
				url: "https://calendar.google.com/xxxx/basic.ics"
				}
			  ]
			}
		},
		{
		module: 'MMM-Wunderlist-Enhanced',
		position: 'middle_center',	// This can be any of the regions. Best results in left or right regions.
		header: '', // This is optional
		config: {
			// See 'Configuration options' for more information.
                        accessToken: "xxxx",  //example token
                        clientID: "xxxx",   //example clientID
                        lists: [xxxx]			
		}
		},
		{
			module: "internet-monitor",
			position: "bottom_left",
			header: "Internet Monitor",
			config: {
				type: "",
				maxTime: 20000,
				updateInterval: 1500000,
				verbose: false,
				displayStrength: true,
				displaySpeed: true,
				strengthIconSize: 20,
				maxGaugeScale: 35,
				wifiSymbol:{
					size: 50,
					fullColor: '#3afc25',
					almostColor: '#ffff0c',
					halfColor: '#ff8c00',
					noneColor: '#ff1111'
				}
			}
		},
		{
			module: "MMM-FreeBox-Monitor",
			position: "bottom_left",
			header: "FreeBox Monitor",
			config: {
				mirrorName: "My Magic Mirror",
				ip: "http://xxx:46575"
				}
		},
		{
			module: 'MMM-Tools',
			position: 'bottom_left',
			header: 'Magic Mirror Status',
			config: {
				device : "RPI", // "RPI" is also available
				refresh_interval_ms : 10000,
				warning_interval_ms : 1000 * 60 * 5,
				enable_warning : true,
				warning : {
				CPU_TEMPERATURE : 70,
				GPU_TEMPERATURE : 65,
				CPU_USAGE : 75,
				STORAGE_USED_PERCENT : 80,
				MEMORY_USED_PERCENT : 80
				}
			}
		},
		{
			module: 'MMM-Hue',
		    position: 'bottom_right',
			header: 'Lumières',
		    config:{
               bridgeip: "192.168.1.253",
		       userid: "xxxx"
				}
		},
		{
			module: 'MMM-TPLink',
			position: 'bottom_right',
			header: 'Prises connectées',
			config: {
			}
		},
		{
			module: "MMM-Remote-Control",
			position: "bottom_bar",
			config: {
				
			}
		},
		],
	paths: {
		modules: "modules",
		vendor: "vendor"
	}
}

if (typeof module !== 'undefined') {module.exports = config;}

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
