### ISSUE TITLE
Where to put this.sendNotification

### ISSUE THREAD

**Issue by MWEL1977** [edward-shen/MMM-pages#15]
Hi there,

I'm just a newbie trying to use your MMM-Pages and MMM-page indicator but I'm stuck!
I did the git pull..... changed the config.js file but were should the "this.sendNotification("PAGE_CHANGED", 2);" go?? In your discribtion it is only mentioned that this must be added to "my code".
But I don't understand what file you mean by that. Perhaps you could ad an example code to the discription were we can see were this piece of code must go?

Hope you can help me.

With kind regards,
Mike Wellink
The Netherlands

**Comment by edward-shen** [comment]
Closing due to age. Please reopen or continue commenting if you still have problems.
