### ISSUE TITLE
Hidden pages

### ISSUE THREAD

**Issue by StuartIanNaylor** [edward-shen/MMM-pages#18]
Is it possible to define max pages to rotate and allow pages after that to only be shown if called by notifications.

Say if I only had one page '0' that only has the default clock and calendar modules then max_pages=1.
Only 1 page so no rotation but after that I can add 'hidden' pages.
Then 'hidden' page 1 would have Calendar-weekly, hidden page 2 would have CalendarExt that are cycled via a notification such as up/down/left/right.
Prob left/right to control your indicator and set page when pages > 1 so likely up/down to change what would be views for that page?

So the above would look something like:-

{
			module: "MMM-pages",
			config: {
                        modules:
                        [ [ [ "calendar", "compliments" ], [ 1, 2] ],
                        [ "MMM-CalendarWeek" ],
                        [ "MMM-CalendarExt" ]
                        ],
			fixed:	[ "clock", "MMM-page-indicator" ],
			animationTime: 4\*1000,
			rotationTime: 30\*1000,
                        maxPages: 1,
                        viewNotifications: [ "Page_up", "Page_down" ]
					}
}

**Comment by edward-shen** [comment]
Hey! Thanks for the Issue!

Are you looking for hidden pages (e.g. pages that aren't shown by MMM-page-indicator and aren't cycled through via the automatic cycle) or subpages (e.g. one page has two pages and you can move between on that page)?

For the former, I think that shouldn't be too difficult to do, but working in subpages will likely involve a little more time.

In any case, I'll need some time to do both as I'm juggling between internship searching and college work.

**Comment by edward-shen** [comment]
Closing due to age. Let me know if you still want this.

**Comment by edward-shen** [comment]
Heads up, your feature request was implemented thanks to @skuethe! Check out the readme for updated instructions on using it!
