### ISSUE TITLE
Timer to change pages?

### ISSUE THREAD

**Issue by gmglickman** [edward-shen/MMM-pages#2]
How about adding the ability to automatically rotate through pages every xx seconds, in addition to reacting to notifications? 
I know it can be done with Carousel, but this seems cleaner.

**Comment by edward-shen** [comment]
This is a planned feature, but due to my laptop being in repair, it'll take a few days to get it implemented. Sorry!

**Comment by edward-shen** [comment]
Sorry it took so long, but this feature has now been implemented. You can update your module by doing `git pull` while in `modules/MMM-pages`!

I'm closing this issue, but feel free to make a new one if you have any issues with the feature.

**Comment by gmglickman** [comment]
Thank you very much.
