### ISSUE TITLE
PAGE_DECREMENT with 'payload: null,' not working as expected

### ISSUE THREAD

**Issue by lxne** [edward-shen/MMM-pages#22]
**Describe the bug**
I tried to use PAGE_DECREMENT with 'payload: null,' activated by a GroveGesture but it didn't work. I had to use 'payload: 1,' for it to operate correctly. PAGE_INCREMENT works well with 'payload: null,'.

The problem seems to be the minus right before 'payload' in the following part of MMM-pages.js
```
      case 'PAGE_DECREMENT':
        Log.log('[Pages]: received a notification to decrement pages!');
        this.changePageBy(-payload, -1);
```
I changed the last line to `this.changePageBy(-(payload, 1));` and it works for me with payload null.

**To Reproduce**
1. Try to use PAGE_DECREMENT with 'payload: null,'

**Expected behavior**
Navigate to previous page.

**Please fill out the following information;**
 - Node version: 10.16.1
 - Have you updated to the latest MagicMirror core? yes
 - Please post the relevant part of your config file here:
```json
        "LEFT": {
          notificationExec: {
            notification: "PAGE_DECREMENT",
            payload: null,
          }
        },
```
**Additional context**

**Comment by edward-shen** [comment]
Thanks for the (complete!) bug report!

The problem is because of Javascript's loose typing. `-null` is coerced into `-0` because `-` operates on a number, and `null` is a falsey statement, so it becomes `0`.

I've just posted a fix. Let me know if the problem persists.

**Comment by lxne** [comment]
Thank you, too.
Fix works just fine.
