### ISSUE TITLE
Doesn't work with MMM-TFL Arrivals

### ISSUE THREAD

**Issue by sparx266** [edward-shen/MMM-pages#25]
Hello

The MMM-TFL-Arrivals doesn't show anything when run in MMM-Pages.
When run without MMM-Pages it works fine.

The config looks like this:

	modules: [
		
                {module: 'MMM-pages',
                config: {
                modules:
                    [[ "MMM-TFL-Arrivals"],
                     [ ""],
                     [ ""],
                     [ ""],
                     [ ""],
                     [ ""],
                     [  ""],
                     [ "" ],                     
                     [ ""],
                     [ ""]],
                fixed: ["MMM-page-indicator"],
                rotationTime:"0",
                }
                },

                  {
		  module: 'MMM-TFL-Arrivals',
	          position: 'top_left',
	          header: "Bus Arrivals",
	               config: {
		       app_id: "", //keys removed,
		       app_key: "", //Keys removed
		       naptanId: "", // StopPoint id removed
		       animationSpeed: 1000,
		       fade: true,
		       fadePoint: 0.25, // Start on 1/4th of the list.
		       limit: 5,
		       initialLoadDelay: 5,
		       color: true,
		       debug: false
		},
		
			}
	
	]
 Any idea what is causing the blank/black screen with MMM-Pages?

Thanks in advance.

**Comment by edward-shen** [comment]
What happens if you remove all those extra pages? e.g. just have modules be equal to `[["MMM-TFL-Arrivals"]]`?

You're also free to remove `rotationTime`, as the default value is zero.

If that doesn't work, can you hit `ctrl+shift+i` when running the magic mirror application? a console window should appear that gives the output of the magic mirror. Can you **attach** that output here?

**Comment by sparx266** [comment]
Removing the other pages didn't change anything.
Or removing rotationTime.

I have attached the console output which is identifying the stop name and buses correctly, just not displaying them when in MMM-Pages.

Thanks for your help on this.

[Console.zip](https://github.com/edward-shen/MMM-pages/files/3884419/Console.zip)

**Comment by edward-shen** [comment]
Please attach the full console log. The log you provided does not assist in debugging the interaction between TFL arrivals and MMM-pages.

**Comment by sparx266** [comment]
Thanks Edward

I don't know how to do this!
Please can you describe how to get the information?
This would also be useful for other modules which may require troubleshooting. 

Thanks again

**Comment by edward-shen** [comment]
I've already explained how to do so in my previous comment—You'll need to hit `ctrl+shift+i` while running magic mirror with a keyboard attached to the pi. Then you should navigate to the console tab, and save the console log to disk.

**Comment by sparx266** [comment]
[Logs.zip](https://github.com/edward-shen/MMM-pages/files/3907582/Logs.zip)
Is this what you are after?

**Comment by edward-shen** [comment]
Hey, that's the right step, but still not correct. What you posted were the console logs of the service running Magic Mirror (btw two of those files were empty). I'm looking for the application logs. You need to view the Magic Mirror application itself and hit `ctrl+shift+i` as that will bring up the chromium logs, which reports runtime errors.

**Comment by sparx266** [comment]
OK, this is where I am getting lost.
Where are these log files saved to please?

**Comment by edward-shen** [comment]
They're not being saved anywhere; they are runtime logs you would see if you hit `ctrl+shift+i` on chrome or firefox.

**Comment by sparx266** [comment]
Yes.
You were sent what can be seen previously with those institutions.

If there is something I'm missing or directions that will help to
understand why things are not working correctly, please let me know in
small, simple sreps.

Best regards

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
