### ISSUE TITLE
Switching Pages with MMM-ModuleScheduler leads to blank page

### ISSUE THREAD

**Issue by rabbit83ka** [edward-shen/MMM-pages#26]
Hi,

I'm trying to switch the pages with ModuleScheduler. But it doesn't change the page, it just "leaves" the pages (no page highlighted in page indicator, no page shown). Any hints whats wrong with my config.js?
```
{
    module: 'MMM-ModuleScheduler',
    config: {
        notification_schedule: [{
                notification: 'PAGE_CHANGED',
                schedule: '0 7 * * 1-5',
                payload: {
                    type: "notification",
                    message: 0
                }
            },
            {
                notification: 'PAGE_CHANGED',
                schedule: '30 5 * * 1-5',
                payload: {
                    type: "notification",
                    messsage: 1
                }
            }
        ]
    }
}
```
Regards
Jan

**Comment by edward-shen** [comment]
(Heads up, I've edited your post for formatting!)

As a quick test, can you set payload to just `1` and `0`? Something like this:

```
{
    notification: 'PAGE_CHANGED',
    schedule: '30 5 * * 1-5',
    payload: 1,
}
```

I think that's what you need to fix it. If that doesn't work, do you mind posting your MMM-Pages config as well?

**Comment by rabbit83ka** [comment]
That works. Thanks a lot!
