### ISSUE TITLE
emit notifications about current page sequence to other modules

### ISSUE THREAD

**Issue by rubenix** [edward-shen/MMM-pages#28]
Hello wrote a post on MM forums [here](https://forum.magicmirror.builders/topic/11568/hi-there-is-a-new-alexa-module/79?page=8)

Im trying to integrate MMM-pages with [MMM-CalendarExt2](https://github.com/eouia/MMM-CalendarExt2) but cannot find a way to accomplish that...and Im think its because the NOTIFICATIONS of MMM-pages
Is that even possible BTW? Any help would be really appreciated! 
Thanks so much for your work!

**Comment by edward-shen** [comment]
Hi, thanks for making an issue here. While I don't quite understand your particular problem (I don't use CalExt2 and I'm having trouble visualizing your issue), I do believe that if MMM-pages sent out a page number notification, your problem would be solved, correct?

**Comment by rubenix** [comment]
hey! thank so much for writing here! Have you seen my post on the forum, maybe you could understand my problem; anyway I know what you're telling me about MMM-pages sending a page number notification but to be honest wouldn't know how to integrate it on the config, sorry but am not a coder, learning these days with this lovely project. I really appreciate your and others help to much. willing to hear from you soon.
On the link in the first post you'l see all my modules config. Thanks again! pages & pages -indicator are indeed a must for me!

**Comment by edward-shen** [comment]
I took a look at your post and I'm still unable to understand what's going on; if you could post a picture or two showing the problem I think I'd understand it much better.

**Comment by rubenix** [comment]
I can send you a picture of my 'duplicated calendar' once I call it from Alexa but I think you can imagine that, isnt it? doble calendar on the screen.
Let me clarify and hope you can understand me now:
The think is that MMM-pages rotates well and all pages shows as it should, 5 pages on my mirror and no issues. When I call a page from 'AlexaControl' it switches to the page in a good manner; all pages works fine except the one it has the Calendar (it duplicate the content, double montly calendar view).
Once the calendar got duplicated it overlaps over the next pages too and I think this happens coz I use PAGE_INCREMENT on NOTIFICATIONS (CalendarExt2) while MMM-pages & AlexaControl use PAGE_CHANGED notifications so when I change to that Page the CalendarExt2 dow not now where it is (does not know with view to show).
im looking at MMM-NotificationTrigger but do not know where to start....if you can give me a hand I would really appreciate your help! maybe this module can sort things for me...

I can make a short video (with rotation times short) and then you can maybe understand the whole issue here...Im trying to get help from CalendarExt2 coder but no luck so far...

Thanks so much!

**Comment by edward-shen** [comment]
Interesting. As far as I'm aware, the magic mirror platform makes a new instance of a module every time you specify one in the config.js. MMM-pages works by hiding a module if it's not suppose to be on the next page, and it does so by going through the magic mirror platform APIs, so it shouldn't be invasive at all. Honestly, I don't know what's going on here. 

By chance, do you have a duplicate entry of CalenderExt2 in your config?

**Comment by rubenix** [comment]
I really appreciate your words, thanks.
as per my config I do not have a duplicated entry of the calendar module. Module its fixed on MMM-pages then theres an special config on the views of the calendar as you can see in the config on both MMM-pages & MMM-CalendarExt2 (MM forums)
I hide the view of the calendar on all pages except the second one...
its actually a way to hide its view on custom.css
probably its CalendarExt2 module culprit but so not now what else to do/try....thaaanks so much!

**Comment by edward-shen** [comment]
Hmm, alright! Please feel free to comment and/or reopen this issue if you need anything from the MMM-pages side then.

Cheers!
