### ISSUE TITLE
return changed page number as a result of PAGE_INCREMENT

### ISSUE THREAD

**Issue by rubenix** [edward-shen/MMM-pages#29]
I noticed module has no feature to emit notifications about current page sequence to other modules.

Would be nice that module return changed page number as a result of PAGE_INCREMENT / DECREMENT so, in other words: recognize which page the Mirror is at that moment because (in my mirror) CalendarExt2 cannot know what scene to show.
If thats implemented I can sync the scene to that number easily and use different scenes for my purpose without worries about page number.

Im trying to get MMM-pages,  MMM-Calendarext2, MMM-AlexaControl, MMM-PageIndicator & MMM-GroveGestures working together and have several problems as I want to send to calendarext2 a notification to change the view but without changing the page. With the help of MMM-NotificationTrigger I can fire QUERY_PAGE_NUMBER but can't accomplish the result I want.

Sorry to open an issue here but don't know if you follow magicmirror forums...Many modules involved and cannot find a clear way to deal with.

Thanks in advance!

**Comment by edward-shen** [comment]
Is this related to #28?

MMM-pages now sends a notification, `"NEW_PAGE"`, on every page update. Let me know if you need anything else.
