### ISSUE TITLE
typo in line 75 of MMM-pages.js

### ISSUE THREAD

**Issue by Ax-LED** [edward-shen/MMM-pages#3]
Hi, is it possible that there is a typo in line 75?
shouldnt it be (mod)
this.curPage = this.mod(this.curPage - 1, this.config.modules.length);
instead of (mode)
this.curPage = this.mode(this.curPage - 1, this.config.modules.length);
?
Regard
AxLED

**Comment by edward-shen** [comment]
Ah-

Thanks for catching that. I've fixed that now. My apologies if it wasn't working for a few days.
