### ISSUE TITLE
Pause & Resume Rotation from notifications

### ISSUE THREAD

**Issue by rubenix** [edward-shen/MMM-pages#30]
It would be nice to add the ability to pause / resume page rotation from notifications. 
ie. pause & resume rotation from a gesture or voice command
I do not know if it is very difficult to implement tho.

Thanks for such a nice module

**Comment by edward-shen** [comment]
I unfortunately cannot test this feature right now, so I won't be pushing this to the master branch yet.

I've implemented this in the `pause-resume-from-notifications` branch. Please let me know if it works for you.

If it works without any bugs (try doing everything to make sure nothing broke), then I'll merge the branch into master.

**Comment by edward-shen** [comment]
I've updated the readme in that branch, so you can take a look at that to see what notifications need to be sent.

**Comment by rubenix** [comment]
WOW, that was fast;
Unfortunately, I cloned from that branch
git clone -b pause-resume-from-notifications https://github.com/edward-shen/MMM-pages.git 
npm install from module directory (just in case) and updated module config to send PAUSE_ROTATION notification but pages continues rotating.
Other notifications seems to work as usual and weren't broken...

**Comment by edward-shen** [comment]
Try again, I've pushed a fix that I think might work.

**Comment by rubenix** [comment]
indeed; its working flawlessly now.
Its a nice feature added, at least for my purposes!
Thanks so much!!

**Comment by edward-shen** [comment]
Glad to be of help.
