### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by DhruvTube** [edward-shen/MMM-pages#31]
Where should I add:
this.sendNotification("PAGE_CHANGED", 2);
because I for some reason cannot see where to add this.

**Comment by edward-shen** [comment]
What are you trying to do? If you're trying to change pages, you either need to set up another module to interact with this one or set up the auto-rotation timer in the config.

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
