### ISSUE TITLE
Is this module able to get notification from a python script

### ISSUE THREAD

**Issue by sgarg15** [edward-shen/MMM-pages#32]
After tons of research and trying the modules that already exist, i havent able to find any module that works well for using ultrasonic sensors to detect swiping motion. so i am thinking, if i can make a python script that detects a swiping motion, am i able to use that to turn pages on the magicmirror?
so if i have something like this 
```
def swiper():
  #code here to detect swipe
  if leftSwipe:
    #send a notification to pages to go left
  if rightSwipe:
    #send a notification to pages to go right
```
Can the pages module accept notification from a outside source like a python script?

**Comment by edward-shen** [comment]
This is more of a question regarding interop between modules and external features in general, but for the most part the answer is no, not for any module by itself.

Check out [Jopyth/MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control), specifically their [API page](https://github.com/Jopyth/MMM-Remote-Control/blob/master/API/README.md) which gives provides instructions to use that module as an HTTP proxy to send Magic Mirror notifications. This should provide you with a method to send notifications from Python, through Python's `http` stdlib.

Let me know if that satisfies your answer.

**Comment by edward-shen** [comment]
I'm closing this issue due to a lack of response. Please feel free to reopen this issue if you still have a problem.
