### ISSUE TITLE
Thanks you for your great work ! 

### ISSUE THREAD

**Issue by pandeyprakhar00** [edward-shen/MMM-pages#33]
@edward-shen

Thank you for building this module, which allowed me to build my own version of Magic Mirror !

https://www.youtube.com/watch?v=sCetiJk2Qus&list=PLBy3Sw0lBrNeihCn0fOr-m5RYJNb4w4IS

🥇

**Comment by edward-shen** [comment]
Glad to be of help and I'm happy that you found it useful!
