### ISSUE TITLE
Weather module

### ISSUE THREAD

**Issue by hm1234** [edward-shen/MMM-pages#38]
**Describe the bug**
Every time I add my current weather module to the first page it would get stuck in the loading page. However if I remove it and move it to the second page it will load.
**To Reproduce**
(Please paste any information on reproducing the issue, for example:)

Add current weather module to the config file.
Add the module name to the first row for page one. (stuck on loading)
Remove from first page and add to the second and it loads.

**Expected behavior**

The current weather to display on the top right.

**Screenshots**
If applicable, add screenshots to help explain your problem. If you believe you
have aptly described your issue in words, feel free to ignore/delete this section.
Don't have any screenshots right now but will try to add some once I get some.
**Please fill out the following information;**
 - Node version: [This can be obtained by running `node --version`]
v10.21.0
 - Have you updated to the latest MagicMirror core? [yes/no]
Yes
 - Please post the relevant part of your config file here:
```json
(Paste the part of the config file here)
```
    {
        module: 'MMM-pages',
        config: {
                modules:
                    [
                     [ ],
                     [ "newsfeed", "currentweather"],
                     [ "calendar", "weatherforecast","MMM-COVID19","MMM-PrayerTime"],
                    ],
                fixed: ["clock", "MMM-NowPlayingOnSpotify", "MMM-page-indicator"],
            }
        },
 - Please post any errors you see about MMM-Pages in the console (Hit F12 > Console when the Magic Mirror window is focused), or write **None** if there aren't any:
```
```
None
**Additional context**

Again, I'd like to apologise for my previous post. I should have read through. Sorry.

**Comment by hm1234** [comment]
{
        module: 'MMM-pages',
        config: {
                modules:
                    [
                     ["currentweather"  ],
                     [ "newsfeed"],
                     [ "calendar", "weatherforecast","MMM-COVID19","MMM-PrayerTime"],
                    ],
                fixed: ["clock", "MMM-NowPlayingOnSpotify", "MMM-page-indicator"],
            }
        },



Issue happens when I set it like this

**Comment by edward-shen** [comment]
Whoops, sorry, I didn't see this post before posting my response on the first issue you made.

Can you try just having the default modules? A lot of the time weird issues like this occur because another module isn't playing nicely with MagicMirror. Something like this:
```
modules: [
  [ "currentweather" ],
  [ "newsfeed" ],
],
fixed: [ "clock" ]
```
And seeing if that works?

**Comment by hm1234** [comment]
OKay just tried not luck
![Annotation 2020-06-04 233507](https://user-images.githubusercontent.com/13208530/83834381-34e97900-a6bc-11ea-8c45-1aee9edd61a9.png)
![Annotation 2020-06-04 233527](https://user-images.githubusercontent.com/13208530/83834382-35820f80-a6bc-11ea-80af-07009bab19f0.png)

**Comment by edward-shen** [comment]
Hmm, are you able to access the console by any chance? Can you try `ctrl` + `shift` + `i`, and then navigating to the console tab? And post your entire config file while you're at it. I don't think it's a config problem, but it doesn't hurt to check.

**Comment by hm1234** [comment]
OKay resolved the issue. it was telegram bot I removed it and it started to work again

**Comment by hm1234** [comment]
thanks for the help @edward-shen

**Comment by edward-shen** [comment]
Didn't quite help, but I appreciate it nonetheless.

Feel free to message the MMM-TelegramBot with your issue as your next steps. I'm sure they'd want to figure that out—it's a pretty serious bug in my opinion.

**Comment by hm1234** [comment]
Will do! Thanks for your work!
