### ISSUE TITLE
how to change pages?

### ISSUE THREAD

**Issue by 8acoustic** [edward-shen/MMM-pages#39]
I'm using  GroveGesture Sensor(PAJ7620u2) MMM-GroveGestures
how to use change pages?

**Comment by edward-shen** [comment]
As @eouia has said in eouia/MMM-GroveGestures#17, you need to send a supported notification from MMM-GroveGestures. The supported notifications that MMM-pages listens to are well documented in the readme.

I do not provide support for configuring external modules, as that would be impossible for a single person.

If you are still confused, perhaps it may be better to ask for help in the [Magic Mirror Forums](https://forum.magicmirror.builders/).

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
