### ISSUE TITLE
MMM-Pages only works in an intranet browser not on the mirror itself

### ISSUE THREAD

**Issue by McNose** [edward-shen/MMM-pages#4]
Hi Edward,

first of all I want to thank you for your great work. The MMM-pages ist exactly what I am looking for.
I installed it and the MMM-page-indicator as well.

However, the mirror itself always shows every modul installed. No matter what page I open. It does not hide or show anything. I always see a 100 percent.
If I open the magic mirror in a intranet browser, the MMM-pages is working fine. I only see, what I configured in the config.js.

The MMM-page-indicator ist working fine. Even on the mirror itself it changes the radio buttons.

Do you have any idea what the problem might be? 
Is it me or may the module might have a bug?

Thank you very much.

Greetings from Germany
McNose

**Comment by edward-shen** [comment]
Hello! Thanks so much for using my module! I'm currently out of town for
the weekend, but I think I know what's the problem. Give me a day or and
I'll see if I can fix it.

I wont be able to test if my fixes work, so please bear with me if my fixes
don't work.

Thanks,
Eddie

**Comment by McNose** [comment]
Hey Eddie,

I am not that familar with github. I just went to the modul folder updating it by the "git pull" comand, right?
The MMM-pages.js was updated but unfortunately with no success. The mirror still shows every modul installed.
Sorry for that.

**Comment by edward-shen** [comment]
Yup!

Try again, this time it should work. If it doesn't I'll need to ask you to post some debug info, like node version (`node --version`) and try to update to the latest version of Magic Mirror (do `git pull && npm install` in the install directory).

**Comment by McNose** [comment]
Hi,
unfortunately it is still not working.
I updated the Magic Mirror by git pull and npm install. And I updated the node version from 6.12.3 to 8.11.1. Still no success.
Do you need any further information? Screenshots or my config?
Thanks.

**Comment by edward-shen** [comment]
Yes, please post the relevant part of your config file. Can you also press F!2 while the MagicMirror is running, go to the console tab, and see if there's any errors about MMM-pages?

**Comment by McNose** [comment]
I just startet the `npm start -dev` command.
For some modules like MMM-pages no helper is found. (Don´t know what it is, but other moduls work without helper).

Later on there are some error messages. Here the part about MMM-Pages.

ERROR! Could not validate main module js file.
/home/pi/MagicMirror/modules/MMM-pages/MMM-pages.js:113
          );

Seems  like there is a ");" too much?
But why is it workling on my intranet browser?

Where else do I find error messages? (Using SSH)

**Comment by McNose** [comment]
My config.js looks like this:

> modules: [
> 		 {
>         	module: 'MMM-pages',
>         	config: {
>                 modules:
>                     [[ "weatherforecast", "updatenotification", "MMM-syslog", "MMM-WunderGround24Hours", "MMM-DWD-WarnWeather", "MMM-RSS-FEED" ],
>                      [ "calendar", "newsfeed", "compliments"]],
>                 excludes: ["MMM-Podcast", "clock", "currentweather", "alert", "MMM-page-indicator", "MMM-GESTURES", "MMM-Remote-Control"],
>      			}
>    		},
> 		{
> 			module: "alert",
> 		},

and so on

**Comment by edward-shen** [comment]
I think I might have solved the issue. Try now.

The helper is an additional script that modules can use to assist the main module. Since MMM-pages is small enough, we don't need one.

**Comment by edward-shen** [comment]
I think I might have solved the issue. Try now.

The helper is an additional script that modules can use to assist the main module. Since MMM-pages is small enough, we don't need one.

**Comment by McNose** [comment]
Awesome. Now it works. Thank you so much!!

**Comment by edward-shen** [comment]
Glad to see it fixed! Sorry for introducing a regression haha.

Please feel free to make another issue if something breaks/feature request/etc!

**Comment by hco125** [comment]
I am having this same problem with additional issues. I have tried with MMM-Carousel module and have the same issue. All modules are showing on one page only and no advance to another page is occuring, either on a browser pointed to the MagicMirror URL, nor on the MagicMirror itself. I am running with pm2 on lastest version of MagicMirror 2.5.0. 

Another problem is that MMM-ModuleScheduler is not hiding the modules I specify. I wonder if the two are interfering with each other.

MMM-Pages config:
'''
		{
			module: 'MMM-pages',
			config: {
				modules: 
					[['MMM-GoogleTasks', 'MMM-Gas', 'MMM-AlarmClock', 'MMM-NOAA3'],
					['MMM-SimpleLogo', 'MMM-CalendarExt']],
				excludes: ['alert', 'updatenotification', 'clock', 'MMM-Remote-Control'],
				animationTime: 0,
				rotationTime: 5000,
				delayTime: 0,
			},
		},
'''

MMM-ModuleScheduler config
'''
		{
			module: 'MMM-ModuleScheduler',
			config: {
				notification_schedule: [
					//TURN SCREEN ON AT 05:00 AM EVERY DAY
					{notification: 'REMOTE_ACTION', schedule: '30 5 * * *', payload: {action: 'MONITORON'}},
					//TURN SCREEN OFF AT 01:00 AM EVERY DAY
					{notification: 'REMOTE_ACTION', schedule: '00 1 * * *', payload: {action: 'MONITOROFF'}},
					//RESTART THE RASPBERRY PI DAILY AT 02:00 AM
					{notification: 'REMOTE_ACTION', schedule: '00 2 * * *', payload: {action: 'REBOOT'}},
				],
				schedulerClass: 'scheduler',
				animationSpeed: 0,
				global_schedule: {
					from: '00 0 * * *',
					to: '01 0 * * *',
					groupClass: 'hide_module',
				},
			},
		},
'''

And this module does not hide:
'''
		{
			module: 'MMM-AlarmClock',
			position: 'top_center',
			classes: 'hide_module',
			config: {
				alarms: [
					{
						time: '09:27', //must be 24 hr format
						days: [1,2,3,4,5], //Sunday=0, Saturday=7
						title: 'KBRX - Party Line',
						message: 'Party Line',
						sound: 'http://162.244.81.209:8032/stream?autoplay=1',
						volume: 1.0,
						touch: false,
						format: 'ddd, h:mm A',
						timer: 1.15 * 60 * 60000, //change first operand to specify hours
						fade: false,
						fadeTimer: 60 * 1000, //change 1st operand to specify seconds, how long fade into alarm before volume is set
						fadeStep: 0.005, //0.5%, inc volume this percent amount each second until fadeTimer is reached
						popup: false,
					},
				],
			},
		},
'''

**Comment by edward-shen** [comment]
Hey @hco125, thanks for reaching out.

You said that your issue you're having occurs both in MMM-Carousel and MMM-pages? That usually indicates that there's a module that doesn't like neither of them.

> and MMM-CalendarExt never shows at all.

Please try disabling that module (commenting out its config section and removing all references to it)  and see if MMM-pages works first. When a module never shows, it's indicative that it errored out. When that happens, MMM-pages will glitch out as well, as it tries to do stuff with a broken module.

Next, a quick test to find if something's up is to go to the console; but you said that nothing showed up? Try hitting `ctrl + shift + i`. If that doesn't work, try hitting f12 or that key combo on a browser with MagicMirror. Next, go to the console tab, and see if there are any errors reported by a module. If there are, this usually causes issues. If you can, please **attach** the entire console log and upload it here. You can do so by right clicking the console and hit "save as".

A slower, more thorough method is to disable all modules and slowly add one by one until this module breaks. It's a tedious job, but it's usually a surefire way to figure out what module isn't working.

----

I took a quick look at the source code and it doesn't look like there's anything that would cause issues with visibility for MMM-AlarmClock. It's possible that a bad config might cause it to always show up. You should double check with that and make sure all values are ok.

---
Finally, for your scheduler problem, it looks like your config is bad:
```
{ from: '00 0 * * *', to: '01 0 * * *' }
```
means that it will hide itself at 00:00 everyday until 00:01 (aka only for one minute). Is this what you wanted?

**Comment by edward-shen** [comment]
I believe it's possible to have something run in the background by simply not specifying a position in the respective module config. 

As for the MMM-googletasks, feel free to create a new issue if collaboration is needed to make a fix for it.

**Comment by hco125** [comment]
Thanks, edward-shen! Sorry for the inconvenience. I created an issue in the MMM-GoogleTasks module, and also thank you for the heads up on not specifying a position to hide a module. Such a simple thing that  I was really over-thinking!
