### ISSUE TITLE
modules of different sizes on the sides

### ISSUE THREAD

**Issue by jasimi** [edward-shen/MMM-pages#41]
Hello
I noticed that some modules have different sizes on pages 2 and 3. How or where do I have to change what so that my modules have a uniform size on the pages.

**Comment by edward-shen** [comment]
Sorry, can you give an example of what you mean? MMM-pages has no control over what size your modules are.

**Comment by jasimi** [comment]
Please note the width of the left modules.
They are the widest on page 1, they narrow on page 2 and the narrowest on page 3.

> 
![2020-07-12 10 44 11](https://user-images.githubusercontent.com/61836987/87242787-3c750e00-c430-11ea-93a9-7c8a88565565.jpg)
![2020-07-12 10 44 03](https://user-images.githubusercontent.com/61836987/87242788-3f6ffe80-c430-11ea-86da-3cab6eb14f6c.jpg)
![2020-07-12 10 43 55](https://user-images.githubusercontent.com/61836987/87242789-4139c200-c430-11ea-80f9-2b7b83a03c2e.jpg)

**Comment by edward-shen** [comment]
The modules that you use are expanding the width, and MMM-Pages has no control over that. You'll need to implement custom css to fix this.

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
