### ISSUE TITLE
Config Request: Set custom default page

### ISSUE THREAD

**Issue by cluelesscarter** [edward-shen/MMM-pages#43]
**Is your feature request related to a problem? Please describe.**
I'm using GroveGestures to send a notification to increase or decrease page numbers to Pages, and I'd like to start out on 'Page 2' so I can go left or right from 'home'.

**Describe the solution you'd like**
A config option to set the default page to whichever page I like.

**Describe alternatives you've considered**
None really, :s 

**Additional context**
thanks man! awesome Module...

**Comment by edward-shen** [comment]
Thanks for the feature request. I don't have a magic mirror present, but these changes were small enough that I think you can help me test them.

Please do the following:
```
git pull
git checkout default-page
```
and then look at the updated configuration options in the `README.md`.

Please let me know if this works.

**Comment by cluelesscarter** [comment]
Hey I just left for a holiday so will do when I return! 

Thanks,
Matthew Carter

www.matthewcarter.co.uk

**Comment by cluelesscarter** [comment]
Hey @edward-shen 

Thanks for this - it works but the Pages-indicator does not display the correct page, on load, the correct homePage is displayed but pages indicator displays the 1st position until you begin navigating.

**Comment by edward-shen** [comment]
Thanks for testing it out. Do a `git pull` and try again—I think I fixed your problem.

**Comment by edward-shen** [comment]
Hey, are you still there? I'd like to get this merged into master so everyone can use it, but I'm not able to until I get confirmation that this works.

**Comment by cluelesscarter** [comment]
@edward-shen Hi Edward, apologies for the slow response I will test it tonight after work!

I'm quite new to github and did a pull request, I think it worked but I'm not 100% sure. I will check again tonight :)

**Comment by edward-shen** [comment]
Can I assume everything's working fine?

**Comment by edward-shen** [comment]
I'm going to assume this branch is fine, since there hasn't been any complaints since.
