### ISSUE TITLE
Page refresh for every switch

### ISSUE THREAD

**Issue by mlcampbe** [edward-shen/MMM-pages#44]
I'm going to ignore the bug report template for now as I am not sure if this is a bug or enhancement or neither. Let me know if you prefer me to ask it differently.

I have setup MMM-Pages to have 2 pages -- the first page has my static stuff (clock, calendar, etc...) and a 2nd page loads the MMM-iFrame-Ping module which loads a URL from my weather station (see https://www.reddit.com/r/raspberry_pi/comments/il03rk/i_made_weather_station_app_and_designed_it_for_a/) as the only item on the 2nd page. 

This all works but it appears that when the pages change either MMM-Pages or MMM-iFrame-Ping is actually re-rendering the URL from the weather station. Because the weather station uses external API's to build the page there is a limit on the number of times these can be called during a hour/day and I do not wish to exceed that. I can see that when using tcpdump and looking for outgoing calls to rainviewer.com a call is made everytime MMM-Pages switches to that page.

Can you confirm if MMM-Pages is doing a reload of the page or do you think this may be related to the iFramePing module?

**Comment by edward-shen** [comment]
Looks like it's related to the iFramePing module, and is intentional. From their readme:
> If the iFrame-Ping module is hidden (by REMOTE-CONTROL or any Carousel module for example), the iFrame will not be updated. As soon as one MMM-iFrame-Ping module will be again displayed on the screen, an update will be requested.

You should request a config option there to disable this feature.

**Comment by mlcampbe** [comment]
Thanks let me go down that route and see what happens.

**Comment by edward-shen** [comment]
Sure. I'm going to close this issue, but feel free to re-open if they bounce it back to me.
