### ISSUE TITLE
Bug after npm install i get Unable to find electron's version number, either install it or specify an explicit version

### ISSUE THREAD

**Issue by robudus** [edward-shen/MMM-pages#45]
**Describe the bug**
after npminstall inside ~/MagicMirror/modules/MMM-Swipe
i get this errors

pi@smartmirror:~/MagicMirror/modules/MMM-Swipe $ npm install

> MMM-Swipe@1.1.1 postinstall /home/pi/MagicMirror/modules/MMM-Swipe
> electron-rebuild -e ../../node_modules/electron-prebuilt

An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at /home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:87:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-Swipe/node_modules/electron-rebuild/lib/src/cli.js:6:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! MMM-Swipe@1.1.1 postinstall: `electron-rebuild -e ../../node_modules/electron-prebuilt`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the MMM-Swipe@1.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-26T13_44_20_466Z-debug.log

**To Reproduce**
(Please paste any information on reproducing the issue, for example:)

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If you believe you
have aptly described your issue in words, feel free to ignore/delete this section.

**Please fill out the following information;**
 - Node version: [This can be obtained by running `node --version`]
v10.22.1
 - Have you updated to the latest MagicMirror core? [yes/no] yes
 - Please post the relevant part of your config file here:
```json
(Paste the part of the config file here)
```
 - Please post any errors you see about MMM-Pages in the console (Hit F12 > Console when the Magic Mirror window is focused), or write **None** if there aren't any:
```
```
**Additional context**

Version:
pi@smartmirror:~/MagicMirror/modules/MMM-Swipe $ python3 --version
Python 3.7.3
pi@smartmirror:~/MagicMirror/modules/MMM-Swipe $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by edward-shen** [comment]
Er, this error message is from MMM-Swipe, not MMM-pages. Consider opening an issue with them?

**Comment by robudus** [comment]
O sorry you are right

**Comment by robudus** [comment]
MMM-Swipe has read-only repo (issues)

**Comment by edward-shen** [comment]
If that's the case then you're out of luck. The author isn't supporting the module anymore. Your best bet if you still want to use it probably to ask on the MagicMirror forums.
