### ISSUE TITLE
[feature request] Have the option to start (some) "fixed" modules hidden

### ISSUE THREAD

**Issue by skuethe** [edward-shen/MMM-pages#47]
**Is your feature request related to a problem? Why do you want this feature?**
I am using MMM-pages with MMM-Touch on a touch display and have a heavy touch related configuration setup f.e. to activate a "screensaver" mode when sliding down (which hides a lot of "fixed" modules and shows others (which are paused on start-up)

**Describe the solution you'd like**
I am thinking about a `fixedStartHidden` array which uses the already implemented "pause / hiding" feature (used for modules on "other" pages) to also hide modules which are present in **both** arrays: `fixed` and `fixedStartHidden` (or however you want to name it :) ). With this feature I can have a "startHidden" option for other third party modules without the need to modify each and every one of them.

**Additional context**
Wanted to get your opinion about this before creating any PR.

**Comment by edward-shen** [comment]
Thanks for the interest—I'll always appreciate a PR, even out of the blue!

Do you mind explaining your situation in more detail? Specifically, what's the current problem you're having? I'm having a little trouble understanding what you want here.

Do you plan on showing them with specific pages? Or do you want them to run all the time? If you only want them to show on specific pages, then it's not really a fixed module. If you want to run them all the time but remain hidden, you can always just not specify a position for that module's config and never mention it in the MMM-pages config. That way, MM won't put it anywhere but keep it running and MMM-pages won't try to hide/pause it.

**Comment by skuethe** [comment]
Thank you for the fast response, sure I'll try to give more details on my situation :)

My idea is to have multiple "modes" (see [MMM-Touch](https://github.com/gfischershaw/MMM-Touch/wiki/Manual#gesturecommands) which are switchable with touch screen usage. So f.e.:

- a `default` mode, which shows `clock`, `weather`, `calendar` on the first page and is the default mode on startup. `clock` is also present in the `fixed` array to always show (there are three pages in total)
- a `screensaver` mode, which activates when I "swipe up". Activating this mode will "hide / pause ALL modules" (so `clock`, `calendar`, `weather` and the ones on pages two and three) and will then show / resume a module which shows a image slideshow in the background
- a `admin` mode, which activates when I "swipe down". Activating this mode will "hide / pause ALL modules" and will show / resume a module which shows system stats (temperature, cpu/ram, etc.) and a "on screen menu" module, where I can restart MM², reboot the Pi etc.
- ...

Now I have two challenges:

1. For this to work from every page, I have to put the modules "clock", "image slideshow", "system stats" and "on screen menu" into the `fixed` array, otherwise they will be marked "paused" by `MMM-pages` when I am not on the "first page" (f.e.) and are then not shown.
2. As I do NOT want to show the modules "image slideshow", "system stats" and "on screen menu" on startup (since they are not "bound" to the default `mode`), I need to make them "start hidden". Most of these modules do not have such an option build-in

Workaround / fixing things:

Now at first I went ahead and started to fork and modify these modules to have such an "startHidden" config option which, when set to `true`, just pauses the modules directly on startup. But this is making life not easy ;)

I then thought, why not extend this module, since it has all the base structure for it.
So the solution would look like this:

1. `fixed` array contains `clock`, `"image slideshow"`, `"system stats"` and `"on screen menu"`
2. `fixedStartHidden` array contains `"image slideshow"`, `"system stats"` and `"on screen menu"` - so these will directly be paused on startup
3. When I now "swipe up" `MMM-Touch` will pause / hide all modules and resume / show `"image slideshow"`
4. Same for when I "swipe down" with `"system stats"` and `"on screen menu"`

> If you want to run them all the time but remain hidden, you can always just not specify a position for that module's config and never mention it in the MMM-pages config. That way, MM won't put it anywhere but keep it running and MMM-pages won't try to hide/pause it.

So about this: with the explained setup this would then cause problems, because the modules would not show up when "resuming" if they do not have a position configured

I hope this makes things a bit clearer. As this is somewhat a new functionality / extension I wanted to check with you first before putting in the effort.

**Comment by lxne** [comment]
Hi, I was thinking about something quite similar.
"Normal mode" and "guest mode". A third mode like you mentioned "admin mode" would be cool, too.

Normal mode is self explaining.
Guest mode would be activated when guests are around to only show none private stuff.
Admin for admin purposes.

Switching modes via notification.

If I understand correctly this would be possible with your solution.

**Comment by skuethe** [comment]
Please note that the `modes` I am referencing, are a build-in option of [MMM-Touch](https://github.com/gfischershaw/MMM-Touch/wiki/Manual#gesturecommands). So the changes to MMM-pages would only be a supportive one to hide specific `fixed` modules on startup

**Comment by edward-shen** [comment]
Ah okay, so these modes would be separate from any normal pages you'd have, e.g. you could swipe up or down on any page you're on to get into these modes?

This sounds like the idea of "hidden pages" mentioned in #18, where you could go into an alternative set of pages that weren't part of the main rotation of pages.

Are you open to suggestions for the implementation? Here's what I'm thinking of:

1. Implement a config option that lets you define named pages (an object will be fine)
2. Implement notification hooks to switch to these alternative pages
3. (Check if rotation still works)
4. Update hiding and showing logic to accommodate these separate pages.
5. Update docs

This would effectively allow you to achieve the same goal while being very flexible in the implementation - you could just switch to the "admin" page or "screensaver" page instead, and make it easy for others to use these hidden pages as well.

Does this sound reasonable, or is there something that might be problematic for your use case?

**Comment by skuethe** [comment]
> Ah okay, so these modes would be separate from any normal pages you'd have, e.g. you could swipe up or down on any page you're on to get into these modes?

Yes exactly!

> 
> This sounds like the idea of "hidden pages" mentioned in #18, where you could go into an alternative set of pages that weren't part of the main rotation of pages.
> 
> Are you open to suggestions for the implementation? Here's what I'm thinking of:

I haven't thought about such a solution yet, but it sounds very good!
Do in the end I could have a simpler config in MMM-Touch and make things easier defining some hidden pages here. Very nice :)

> 
> 1. Implement a config option that lets you define named pages (an object will be fine)
> 2. Implement notification hooks to switch to these alternative pages
> 3. (Check if rotation still works)
> 4. Update hiding and showing logic to accommodate these separate pages.
> 5. Update docs

Things going through my mind:
1. Module names in the "named pages" config objects would need to be completely "separated" from the normal pages AND the fixed arrays. So f.e. if I have `clock` in the fixed array and also want to show `clock` module on one of the specified named pages, I should be able to do that. Or to put it differently: Creating an "empty" named page (so without any modules) should really show an empty page and ignore everything defined in the fixed array
2. notifications can maybe be as easy as having two. something like `PAGES_RESUME_ROTATION` and `PAGES_SHOW_NAMED` which accepts the page name as a payload


> 
> This would effectively allow you to achieve the same goal while being very flexible in the implementation - you could just switch to the "admin" page or "screensaver" page instead, and make it easy for others to use these hidden pages as well.

Definitely!


> 
> Does this sound reasonable, or is there something that might be problematic for your use case?

Sounds great.
At the moment I can't think of anything problematic about it.

Send from mobile - hopefully without typos

**Comment by edward-shen** [comment]
Let's keep this feature named "hidden pages" rather than "named pages" -- the problem with named pages is that people will then ask for "why can't normal pages be named too?".

> Module names in the "named pages" config objects would need to be completely "separated" from the normal pages AND the fixed arrays. 

This sounds reasonable so long as you document this well in the readme.

> notifications can maybe be as easy as having two. something like `PAGES_RESUME_ROTATION` and `PAGES_SHOW_NAMED` which accepts the page name as a payload

`RESUME_ROTATION` is already a thing. I would rather prefer `SHOW_HIDDEN_PAGE` and `LEAVE_HIDDEN_PAGE`, where `SHOW_HIDDEN_PAGE` accepts a parameter. 

As for the expected config options, I'm expecting something like this:
```js
    {
        module: 'MMM-pages',
        config: {
                modules:
                    [[ "weatherforecast", "newsfeed"],
                     [ "calendar", "compliments" ]],
                fixed: ["clock", "currentweather", "MMM-page-indicator"],
                hiddenPages: {
                      "admin": [ "module1", "module2" ],
                      "guest": [ "module1", "module3" ],
                },
        }
    }
```

If that looks good to you, then you have my seal of approval for the PR. 👍

**Comment by skuethe** [comment]
Cool, I'll have a look at it in the next days :)
