### ISSUE TITLE
[BUG] Modules disapper from pages after rotationHomePage times out

### ISSUE THREAD

**Issue by fnsign** [edward-shen/MMM-pages#49]
**Describe the bug**
Modules disappear from pages after rotationHomePage times out and they don't come back. Pages remain blank. This happens since the latest update of MMM-pages. Before the update everything was fine.

**To Reproduce**
(Please paste any information on reproducing the issue, for example:)
1. Boot into MM. The pages are shown normally with all modules
2. Wait for the time that is adjusted in config.js for rotationHomePage (in my case 130000ms)
3. The page (and all other pages) go blank, only the page indicators remain visible
4. The pages remain blank until I reboot MM.

**Expected behavior**
After rotationHomePage times out the defined homPage should be displayed with its assigned modules

**Screenshots**
If applicable, add screenshots to help explain your problem. If you believe you
have aptly described your issue in words, feel free to ignore/delete this section.

**Please fill out the following information;**
 - Node version: 10.23.0
 - Have you updated to the latest MagicMirror core? yes, 2.13.0
 - Please post the relevant part of your config file here:
```j{
			module: 'MMM-pages',
			disabled: false,
			config: {
				modules:
					[

						// Page 0 -- Magic Clock
						["MMM-TextClock", "newsfeed"],
						// Page 1 -- Hauptseite
						["clock", "newsfeed", "MMM-MyCalendar", "MMM-withings", "MMM-DarkSkyForecast", "MMM-RAIN-MAP", "MMM-DWD-WarnWeather", "MMM-Sonos", "MMM-PublicTransportHafas", "MMM-MyScoreboard", "MMM-COVID19-AMPEL"],
						// Page 2 -- SmartHome
						["clock", "MMM-Netatmo", "MMM-Tools", "mmm-hue-lights", "MMM-Homematic"],
						// Page 3
						["octomirror-module"],
					],
				fixed: ["alert", "updatenotification", "MMM-page-indicator", "MMM-NewPIR"],

				animationTime: 500,
				rotationHomePage: 130000,
				homePage: 0,
			}
		},
```
 - Please post any errors you see about MMM-Pages in the console (Hit F12 > Console when the Magic Mirror window is focused), or write **None** if there aren't any:
see attached screenshot
![Bildschirmfoto 2020-11-06 um 10 54 37](https://user-images.githubusercontent.com/25816647/98355194-1cdaa480-2022-11eb-927d-1121d155dbde.png)
Errors in pm2 logs: ***None***
```
```

**Comment by lxne** [comment]
Got the same issue since last update.

**Comment by edward-shen** [comment]
Thanks for the bug report. Looking into it now.

**Comment by edward-shen** [comment]
Thanks for waiting. There was a typo introduced in the last update that broke this feature. Let me know if you still have problems, and we can re-open this issue.

**Comment by fnsign** [comment]
Thanks for the quick fix! It works now again.
