### ISSUE TITLE
Why not include page indicator?

### ISSUE THREAD

**Issue by E3V3A** [edward-shen/MMM-pages#5]
Hi Edward, 
Your module seem very simple to use, and promising as a low-load replacement of the Carousel. 
However, why did you not include the page indicators directly in this module?

**Comment by edward-shen** [comment]
Hello!

I primarily made it a separate module for modularity. I personally don't like it when I need to install some unrelated thing to use a single feature of it.

By splitting up the module into two, I allow people who want to use MMM-page-indicator for their purposes without requiring them to drag in MMM-pages.

MMM-pages is more versatile than you might think. People have used MMM-pages for personalized pages with face recognition, which doesn't make sense to include MMM-page-indicator.

**Comment by E3V3A** [comment]
Aha, I see. It just seemed more natural to have a config option like: `pageIndicator: true` and not have to install and configure a separate module... I also thought you needed to have MMM-pages in order to use the indicator. Thanks for quick feedback.

**Comment by edward-shen** [comment]
That's a cost that I've found acceptable. I don't see clean and (more importantly) expected way to ask people to install both.

The issue is that other modules need to add in support for MMM-page-indicators for it to properly work.
