### ISSUE TITLE
Does this do some kind of overlay in background?

### ISSUE THREAD

**Issue by AshDarko** [edward-shen/MMM-pages#52]
first of all thanks for your time and effort on this module :)

I have installed this and got this working as intended for now.

And just wondering does it override the "fullscreen_above" position?

Only reason I ask, and its seasonal, is I have MMM-Snow for the kids installed, and the snowflakes seem to fall behind this, instead of in front like they used to before i installed this.

So I guess, any  way to make your layer transparent or...?

No biggy

I have no errors reported, and am on the latest MM

**Comment by edward-shen** [comment]
>  I have MMM-Snow for the kids installed,

Thats adorable!

MMM-pages doesn't mess around with anything like that and it only asks MM to hide and show modules. Any change in behavior would probably be a bug on the module instead, not MMM-Pages.

You can try changing the CSS for MMM-snow and increase the z-index (I believe a higher value is shown on top), but this might be worth filing an issue there as well for visibility. Im not sure how MMM-snow works, so it's probably best to consult their Readme instead.

**Comment by AshDarko** [comment]
Hi! yeah I tried a custom CSS zindex on snow to put it at 1000 and no joy.

Will ask over there too. Thank you for your quick reply!

So yours doesn't add a layer for the page or anything like that?

**Comment by edward-shen** [comment]
Yeah, it doesn't. MMM-pages is just a really fancy way to just ask modules to hide and show themselves all at the same time so they look like they're on a page together :)

**Comment by AshDarko** [comment]
thank you again :)

**Comment by AshDarko** [comment]
I found it, in your pages.css you have a z-index of -1 which is causing the issue :)

**Comment by edward-shen** [comment]
Oh my god, I've completely forgotten about that... When I get a chance I'll pull out that change. In hindsight we really shouldn't be doing something like that, even if it does fix a problem that a user had before.

Sorry for leading you down the wrong path!

**Comment by AshDarko** [comment]
Thats fine no worries! Glad I found it and hope it helps :)

**Comment by edward-shen** [comment]
Alright, I've pulled out the changes in `pages.css`. Thanks again for helping out!
