### ISSUE TITLE
mmm-pages do not work with mmm-traffic

### ISSUE THREAD

**Issue by kusselin** [edward-shen/MMM-pages#53]
hi, i have installed mmm-pages and mmm-traffic. Without pages this modul works o.k., but when i install pages the traffic module doesn‘t show :-(

The same problem is coming with the MMM-OpenWebWeather. Her you can only see „Load“ but the module does‘t show with MMM-pages.

Here is my code in the config.js

`{
    			module: "MMM-pages",
    			config: {
						modules: 
						[[ "MMM-SoccerLiveScore" ],
						[ "MMM-COVID19-AMPEL" ],
						[ "MMM-Formula1" ]],
			fixed: [ "clock" , "MMM-OpenmapWeather" , "weatherforecast" , "MMM-PublicTransportHafas" , "newsfeed" , "calendar" , "MMM-Fuel", "MMM-Tankerkoenig" , "MMM-ioBroker" , "MMM-Traffic" ],
    		rotationTime: 120000,
			}
		},`

Is there anyone who can help me about the mistake?

Thanks

Here is the magicmirro forum link

https://forum.magicmirror.builders/topic/14071/not-all-modules-are-displaying-on-the-tv/22?page=3

**Comment by edward-shen** [comment]
Can you open up the console and see if there are any errors? Generally speaking these types of problems are due to the other modules doing something wired rather than mmm-pages doing something wired.

**Comment by kusselin** [comment]
is this o.k. so? 
`Initializing MagicMirror.
translator.js:129 Loading core translation file: translations/de.json
translator.js:154 Loading core translation fallback file: translations/en.json
loader.js:176 Load script: modules/default/alert//alert.js
module.js:513 Module registered: alert
loader.js:148 Bootstrapping module: alert
loader.js:176 Load script: modules/default/alert/notificationFx.js
loader.js:153 Scripts loaded for: alert
loader.js:195 Load stylesheet: modules/default/alert/notificationFx.css
loader.js:195 Load stylesheet: vendor/css/font-awesome.css
loader.js:155 Styles loaded for: alert
translator.js:100 alert - Load translation: translations/de.json
translator.js:102 alert - Load translation fallback: translations/en.json
loader.js:157 Translations loaded for: alert
loader.js:176 Load script: modules/default/updatenotification//updatenotification.js
module.js:513 Module registered: updatenotification
loader.js:148 Bootstrapping module: updatenotification
loader.js:153 Scripts loaded for: updatenotification
loader.js:155 Styles loaded for: updatenotification
loader.js:157 Translations loaded for: updatenotification
loader.js:176 Load script: modules/default/clock//clock.js
module.js:513 Module registered: clock
loader.js:148 Bootstrapping module: clock
loader.js:176 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:176 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:176 Load script: vendor/node_modules/suncalc/suncalc.js
loader.js:153 Scripts loaded for: clock
loader.js:195 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:155 Styles loaded for: clock
loader.js:157 Translations loaded for: clock
loader.js:176 Load script: modules/default/calendar//calendar.js
module.js:513 Module registered: calendar
loader.js:148 Bootstrapping module: calendar
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: calendar
loader.js:195 Load stylesheet: modules/default/calendar/calendar.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: calendar
loader.js:157 Translations loaded for: calendar
loader.js:148 Bootstrapping module: calendar
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: calendar
loader.js:236 File already loaded: calendar.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: calendar
loader.js:157 Translations loaded for: calendar
loader.js:148 Bootstrapping module: calendar
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: calendar
loader.js:236 File already loaded: calendar.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: calendar
loader.js:157 Translations loaded for: calendar
loader.js:176 Load script: modules/MMM-OpenmapWeather//MMM-OpenmapWeather.js
module.js:513 Module registered: MMM-OpenmapWeather
loader.js:148 Bootstrapping module: MMM-OpenmapWeather
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: MMM-OpenmapWeather
loader.js:195 Load stylesheet: vendor/node_modules/weathericons/css/weather-icons.css
loader.js:195 Load stylesheet: modules/MMM-OpenmapWeather/MMM-OpenmapWeather.css
loader.js:155 Styles loaded for: MMM-OpenmapWeather
loader.js:157 Translations loaded for: MMM-OpenmapWeather
loader.js:176 Load script: modules/default/weatherforecast//weatherforecast.js
module.js:513 Module registered: weatherforecast
loader.js:148 Bootstrapping module: weatherforecast
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: weatherforecast
loader.js:236 File already loaded: weather-icons.css
loader.js:195 Load stylesheet: modules/default/weatherforecast/weatherforecast.css
loader.js:155 Styles loaded for: weatherforecast
loader.js:157 Translations loaded for: weatherforecast
loader.js:176 Load script: modules/MMM-Remote-Control//MMM-Remote-Control.js
module.js:505 Check MagicMirror version for module 'MMM-Remote-Control' - Minimum version:  2.12.0 - Current version: 2.13.0
module.js:507 Version is ok!
module.js:513 Module registered: MMM-Remote-Control
loader.js:148 Bootstrapping module: MMM-Remote-Control
loader.js:153 Scripts loaded for: MMM-Remote-Control
loader.js:195 Load stylesheet: modules/MMM-Remote-Control/remote-control.css
loader.js:155 Styles loaded for: MMM-Remote-Control
loader.js:157 Translations loaded for: MMM-Remote-Control
loader.js:176 Load script: modules/MMM-SoccerLiveScore//MMM-SoccerLiveScore.js
module.js:513 Module registered: MMM-SoccerLiveScore
loader.js:148 Bootstrapping module: MMM-SoccerLiveScore
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: MMM-SoccerLiveScore
loader.js:236 File already loaded: font-awesome.css
loader.js:195 Load stylesheet: modules/MMM-SoccerLiveScore/MMM-SoccerLiveScore.css
loader.js:155 Styles loaded for: MMM-SoccerLiveScore
loader.js:157 Translations loaded for: MMM-SoccerLiveScore
loader.js:176 Load script: modules/MMM-Tankerkoenig//MMM-Tankerkoenig.js
module.js:505 Check MagicMirror version for module 'MMM-Tankerkoenig' - Minimum version:  2.2.0 - Current version: 2.13.0
module.js:507 Version is ok!
module.js:513 Module registered: MMM-Tankerkoenig
loader.js:148 Bootstrapping module: MMM-Tankerkoenig
loader.js:153 Scripts loaded for: MMM-Tankerkoenig
loader.js:195 Load stylesheet: modules/MMM-Tankerkoenig/MMM-Tankerkoenig.css
loader.js:155 Styles loaded for: MMM-Tankerkoenig
translator.js:100 MMM-Tankerkoenig - Load translation: i18n/de.json
translator.js:102 MMM-Tankerkoenig - Load translation fallback: i18n/en.json
loader.js:157 Translations loaded for: MMM-Tankerkoenig
loader.js:176 Load script: modules/MMM-SmartWebDisplay//MMM-SmartWebDisplay.js
:8080/modules/MMM-SmartWebDisplay//MMM-SmartWebDisplay.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:186 Error on loading script: modules/MMM-SmartWebDisplay//MMM-SmartWebDisplay.js
script.onerror @ loader.js:186
loader.js:176 Load script: modules/MMM-ioBroker//MMM-ioBroker.js
module.js:513 Module registered: MMM-ioBroker
loader.js:148 Bootstrapping module: MMM-ioBroker
loader.js:153 Scripts loaded for: MMM-ioBroker
loader.js:195 Load stylesheet: modules/MMM-ioBroker/MMM-ioBroker.css
loader.js:155 Styles loaded for: MMM-ioBroker
loader.js:157 Translations loaded for: MMM-ioBroker
loader.js:176 Load script: modules/MMM-Fuel//MMM-Fuel.js
module.js:513 Module registered: MMM-Fuel
loader.js:148 Bootstrapping module: MMM-Fuel
loader.js:153 Scripts loaded for: MMM-Fuel
loader.js:236 File already loaded: font-awesome.css
loader.js:195 Load stylesheet: modules/MMM-Fuel/MMM-Fuel.css
loader.js:155 Styles loaded for: MMM-Fuel
translator.js:100 MMM-Fuel - Load translation: translations/de.json
translator.js:102 MMM-Fuel - Load translation fallback: translations/en.json
loader.js:157 Translations loaded for: MMM-Fuel
loader.js:176 Load script: modules/MMM-PublicTransportHafas//MMM-PublicTransportHafas.js
module.js:513 Module registered: MMM-PublicTransportHafas
loader.js:148 Bootstrapping module: MMM-PublicTransportHafas
loader.js:236 File already loaded: moment.js
loader.js:176 Load script: modules/MMM-PublicTransportHafas/core/PTHAFASDomBuilder.js
loader.js:176 Load script: modules/MMM-PublicTransportHafas/core/PTHAFASTableBodyBuilder.js
loader.js:153 Scripts loaded for: MMM-PublicTransportHafas
loader.js:195 Load stylesheet: modules/MMM-PublicTransportHafas/css/styles.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: MMM-PublicTransportHafas
translator.js:100 MMM-PublicTransportHafas - Load translation: translations/de.json
translator.js:102 MMM-PublicTransportHafas - Load translation fallback: translations/en.json
loader.js:157 Translations loaded for: MMM-PublicTransportHafas
loader.js:176 Load script: modules/default/compliments//compliments.js
module.js:513 Module registered: compliments
loader.js:148 Bootstrapping module: compliments
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: compliments
loader.js:155 Styles loaded for: compliments
loader.js:157 Translations loaded for: compliments
loader.js:176 Load script: modules/MMM-Tools//MMM-Tools.js
module.js:513 Module registered: MMM-Tools
loader.js:148 Bootstrapping module: MMM-Tools
loader.js:176 Load script: modules/MMM-Tools/configMerge.min.js
configMerge.min.js:1 [@bugsounet] configMerge v1.0.0 Loaded !
loader.js:153 Scripts loaded for: MMM-Tools
loader.js:195 Load stylesheet: modules/MMM-Tools/MMM-Tools.css
loader.js:155 Styles loaded for: MMM-Tools
translator.js:100 MMM-Tools - Load translation: translations/de.json
translator.js:102 MMM-Tools - Load translation fallback: translations/en.json
loader.js:157 Translations loaded for: MMM-Tools
loader.js:176 Load script: modules/MMM-Traffic//MMM-Traffic.js
module.js:513 Module registered: MMM-Traffic
loader.js:148 Bootstrapping module: MMM-Traffic
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: MMM-Traffic
loader.js:195 Load stylesheet: modules/MMM-Traffic/traffic.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: MMM-Traffic
loader.js:157 Translations loaded for: MMM-Traffic
loader.js:148 Bootstrapping module: MMM-Traffic
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: MMM-Traffic
loader.js:236 File already loaded: traffic.css
loader.js:236 File already loaded: font-awesome.css
loader.js:155 Styles loaded for: MMM-Traffic
loader.js:157 Translations loaded for: MMM-Traffic
loader.js:176 Load script: modules/MMM-pages//MMM-pages.js
module.js:513 Module registered: MMM-pages
loader.js:148 Bootstrapping module: MMM-pages
loader.js:153 Scripts loaded for: MMM-pages
loader.js:195 Load stylesheet: modules/MMM-pages/pages.css
loader.js:155 Styles loaded for: MMM-pages
loader.js:157 Translations loaded for: MMM-pages
loader.js:176 Load script: modules/default/newsfeed//newsfeed.js
module.js:513 Module registered: newsfeed
loader.js:148 Bootstrapping module: newsfeed
loader.js:236 File already loaded: moment.js
loader.js:153 Scripts loaded for: newsfeed
loader.js:155 Styles loaded for: newsfeed
loader.js:157 Translations loaded for: newsfeed
loader.js:195 Load stylesheet: css/custom.css
alert.js:162 Starting module: alert
updatenotification.js:19 Start updatenotification
clock.js:46 Starting module: clock
3calendar.js:81 Starting module: calendar
MMM-OpenmapWeather.js:117 Starting module: MMM-OpenmapWeather
weatherforecast.js:90 Starting module: weatherforecast
MMM-Remote-Control.js:23 Starting module: MMM-Remote-Control
MMM-ioBroker.js:52 Starting module: MMM-ioBroker
MMM-Fuel.js:180 Starting module: MMM-Fuel
MMM-Fuel.js:183 Config option sortBy has no matching value in config option types! Falling back to first entry.
start @ MMM-Fuel.js:183
MMM-PublicTransportHafas.js:43 Starting module: MMM-PublicTransportHafas with identifier: module_14_MMM-PublicTransportHafas
compliments.js:38 Starting module: compliments
2MMM-Traffic.js:21 Starting module: MMM-Traffic
newsfeed.js:57 Starting module: newsfeed
main.js:508 All modules started!
MMM-Tools.js:156 MMM-Tools is suspended.
MMM-pages.js:115 [Pages]: received that all objects are created; will now hide things!
module.js:199 alert is suspended.
module.js:199 MMM-pages is suspended.
module.js:199 MMM-OpenmapWeather is suspended.
module.js:199 weatherforecast is suspended.
module.js:199 MMM-Remote-Control is suspended.
module.js:199 compliments is suspended.
MMM-Tools.js:156 MMM-Tools is suspended.
2module.js:199 MMM-Traffic is suspended.
main.js:297 Will not show MMM-OpenmapWeather. LockStrings active: module_6_MMM-OpenmapWeather
main.js:297 Will not show weatherforecast. LockStrings active: module_7_weatherforecast
MMM-Traffic.js:126 received MMM_TRAFFIC_DURATION
module.js:206 clock is resumed.
3module.js:206 calendar is resumed.
module.js:206 MMM-SoccerLiveScore is resumed.
module.js:206 MMM-Tankerkoenig is resumed.
module.js:206 MMM-ioBroker is resumed.
module.js:206 MMM-Fuel is resumed.
module.js:206 MMM-PublicTransportHafas is resumed.
module.js:206 newsfeed is resumed.
api.openweathermap.org/data/2.5/forecast/daily?id=2847614&cnt=7&exclude=false&units=metric&lang=de&APPID=26380623d91b9074706aea691e19698a:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
weatherforecast.js:265 weatherforecast: Your AppID does not support long term forecasts. Switching to fallback endpoint.
weatherRequest.onreadystatechange @ weatherforecast.js:265
MMM-Traffic.js:126 received MMM_TRAFFIC_DURATION
main.js:297 Will not show MMM-Tools. LockStrings active: module_19_MMM-pages
calendar.js:145 Calendar Error. Could not fetch calendar: https://calendar.google.com/calendar/ical/kcb3jqvhnqem58u1jo14q0m00c%40group.calendar.google.com/private-426839fca2c51459341321f6f4e55e84/basic.ics
socketNotificationReceived @ calendar.js:145`

**Comment by edward-shen** [comment]
Looks like they're hiding themselves:

```
main.js:297 Will not show MMM-OpenmapWeather. LockStrings active: module_6_MMM-OpenmapWeather
main.js:297 Will not show weatherforecast. LockStrings active: module_7_weatherforecast
```

MMM-pages is trying to show them but since there's a lockstring on the modules they are refusing to show themselves.

I don't think this is a problem with MMM-pages. I'd consider filing an issue with the respective modules for more help.

**Comment by kusselin** [comment]
Ok and can you say about mmm-traffic? Well, when i kill the pages code mmm-pages from the config.js the weather and the traffic module is displaying.. put i in the mmm-pages code again, the two modules doesn‘t show :-(

**Comment by edward-shen** [comment]
Looks like it's a known issue: SamLewis0602/MMM-Traffic#86

**Comment by SamLewis0602** [comment]
Hey @edward-shen , author of mmm-traffic here. I tried adding my module as a fixed module in my config for pages, but I still see "MMM-traffic suspended" in the console logs when I run the mirror. I don't see any other logging so not sure where else to look. Can you offer some help? Thanks.

**Comment by edward-shen** [comment]
Thanks for the ping. I've left a comment on that issue since I believe I've found the problem—lets move the discussion there.
