### ISSUE TITLE
Page one hidden after Page_Increment / decrement

### ISSUE THREAD

**Issue by McNose** [edward-shen/MMM-pages#6]
Hi Ed,

seems like I found another issue. Guess it happens after your very last update, because I didnt see it when I testet the previous one.

I have got 2 pages and the page indicator. 
When I start the mirror I see page one as defined.
I switch the page using page_increment or decrement. 
I see page two as defined.
I use page_increment / decrement again.
Page one is black except the modules which are excluded by MMM-pages.

Any idea about that?
Please let me know if you need any further information.

Thanks.

**Comment by Ax-LED** [comment]
Hi Ed,
i have the same issue.
It seems style="display: none;" is set one div "to high", see example.

<div class="region top left">
<div class="container" style="display: none;"
><div id="module_3_MMM-MyCalendar" class="module MMM-MyCalendar MMM-MyCalendar" style="transition: opacity 0.5s ease 0s; position: fixed; opacity: 0;">_

Greets
AxLED

**Comment by edward-shen** [comment]
Hello,

I have reverted the newest change in code. Please try pulling now and see if it works.

I apologize for recent problems.

**Comment by Ax-LED** [comment]
Helle Edward,
after pulling your last changes it works again.

Thank you.

AxLED

**Comment by edward-shen** [comment]
@Ax-LED That shouldn't be a problem. CSS would have the every thing contained with in the container div inherit the `display: none;` property.

The module doesn't interact with the HTML layer--that's something that MagicMirror core handles. If that is the problem (and not just me having shit code), then this issue is upstream.

**Comment by edward-shen** [comment]
@Ax-LED Glad to know it works again... Again, I apologize for recent problems in my module. I'll be working on a `dev` branch from now on, which should stop shit code from going through to you guys.

**Comment by edward-shen** [comment]
@McNose Please let me know if that fixes your issue. Then I'll close this issue.

**Comment by McNose** [comment]
Yes. This is it. Works fine again.
Great.
Thank you.

**Comment by edward-shen** [comment]
Again, sorry about that.
