### ISSUE TITLE
Using a module multiple times

### ISSUE THREAD

**Issue by Welldoor** [edward-shen/MMM-pages#61]
I just wonder, maybe this isn't a feature request in first place and I just missed something.

Eg. I have two pages
sport
work

I need my sport events on the sport page and the work events on the work page.

How to configure MMM-pages to show up two different calendar sessions, but both with the same module?

I also want to use two instances of MMM-BackgroundSlideshow, so on the sport page it is sliding through sport pictures and on work page it is sliding work motivation pictures or whatsoever...

**Comment by edward-shen** [comment]
Just have two instances of the same module in your `config.js` with different names. You can configure them separately and have each show up on different pages.

**Comment by Welldoor** [comment]
This means to clone/save it two times in my modules folder, right? Otherwise haven't found anything to give my modules names, wether here nor in the MM documentation.

Thank you!

**Comment by edward-shen** [comment]
Yeah, it's not really well documented on the magic mirror docs but that'll let you do what you want!

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
