### ISSUE TITLE
Automatic page changes influenced by rotationDelay

### ISSUE THREAD

**Issue by drtorchwood** [edward-shen/MMM-pages#64]
Perhaps, I have a wrong understanding of the different timing parameters but it does not show the expected behavior. 
I set the `rotationTime` to 5000 (`rotationDelay`, `animationTime` and `rotationHomePage` not set). However, the pages change automatically every 15 seconds. 
If I additionally set `rotationDelay` to 5000 (instead of the default 10000) the pages change every 10 seconds. 
The combination `rotationTime:10000` and `rotationDelay:5000` results in a 15 seconds cycle. 

It seems that the page change for automatic page change is the sum of `rotationDelay` and `rotationTime`. The manual states for `rotationDelay`: "... how long should a _manual page_ change linger before returning to automatic page changing"

- Node version: v10.24.1
- MagicMirror version: 2.17.1
- MMM-pages: current version

Did I misunderstand the manual, is the manual wrong or is there an error in the module itself?

**Comment by edward-shen** [comment]
Yeah, there's a bug. That was the original intent, but it looks like across PRs bugs were introduced.

Looks like [this](https://github.com/edward-shen/MMM-pages/blob/master/MMM-pages.js#L236-L252) is the current function. Note that we first set a delayed event to fire off, but that delayed event is the `rotationTime` timer. 

That whole function needs to be rewritten to be less jank, but unfortunately I'm limited in capacity of what I can do right now.

I'm open to PRs.

**Comment by edward-shen** [comment]
Closed by #66.
