### ISSUE TITLE
No default weather modules are populating

### ISSUE THREAD

**Issue by matchiznverse** [edward-shen/MMM-pages#65]
Setup the config files and even though the weather previews before the pages module starts all of the weather modules are gone.

When I use ["currentweather","weatherforecast"]  they do not appear if I use ["weather"] the module appears but with the default settings.

==

		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "***",
				locationID: "**", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "***"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "**",
				locationID: "***", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "***"
			}
		},

===

			{
				module: 'MMM-pages',
					config: {
							modules: [
								["currentweather","weatherforecast"],
								["newsfeed","MMM-Reddito"],
								["MMM-Wallpaper"]
								],
							fixed: ["clock", "MMM-page-indicator","MMM-Face-Multi-User-Recognition-SMAI","MMM-Screencast"],
							hiddenPages: {
											"Hidden": [ "MMM-Remote-Control",],
							rotationTime: 10000
                },
        }

**Comment by edward-shen** [comment]
Looks like as part of [`v2.15.0`](https://github.com/MichMich/MagicMirror/commit/491f5aa7769a12de7f20f201de0078704c158a8d) those modules are deprecated. You should use the `weather` module instead (and I should update the docs).

For multiple modules of the same name, please see [this post](https://github.com/edward-shen/MMM-pages/issues/61#issuecomment-938563449) on how to do so, if you really want to do that.

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.
