### ISSUE TITLE
delete a page number with crontan

### ISSUE THREAD

**Issue by chassain** [edward-shen/MMM-pages#68]
Hello,

Is it possible to delete a number page with crontab ? i have multi page in my config and i display airplane departures with 2 pages..9h-15h and 15h-19h..the page after 15h need to be delete and not only hidden.
Thanks

**Comment by edward-shen** [comment]
Sorry, it's not possible. I'd suggest forking and implementing the feature yourself. I don't think this is a good feature for MMM-pages. Dynamic page creation and deletion seem like a huge headache that I personally cannot maintain.
