### ISSUE TITLE
git pull: Please tell me who you are

### ISSUE THREAD

**Issue by McNose** [edward-shen/MMM-pages#7]
Hi Eddie,

sorry for asking you again.
I just wanted to pull the latest version of MMM-pages entering the command `git pull.`
However the console is asking who I am.

> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.

I tried to pull another modul, which works fine. So maybe it is a bug?

Thanks again.
McNose

**Comment by edward-shen** [comment]
Hmm, try deleting the MMM-pages folder and re-cloning it:
```
# in the modules folder:
rm -rf MMM-pages
git clone https://github.com/edward-shen/MMM-pages.git
```
Your settings should still be saved because those are stored in a different folder.

**Comment by McNose** [comment]
Interessting.
I used your commands and could install it without problems.
But the version is still one commit behind, so I tried to pull again.
Same issue as above.

**Comment by edward-shen** [comment]
Have you tried running those values in the original error message?
```
git config --global user.email "foo@example.com"
git config --global user.name "Your Name"
```
It looks like others had issues before with this same problem and was fixed by setting those values.

**Comment by McNose** [comment]
Seems liked it worked.
I tried the `git pull` after these two commands above. It asked something like "would you like to comment", I ignored and now it works.
Strange.
Again...thank you very much for helping!

**Comment by edward-shen** [comment]
No problem. LMK if you have other issues.
