### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by sdetweil** [edward-shen/MMM-pages#72]
i'm ready to be maintainer

**Comment by edward-shen** [comment]
Hey @sdetweil, sorry for a long wait, and thanks for stepping up...?

If you're interested, do you mind making a couple PRs first to this repo? Either addressing some of the (very old) bug reports or new contributions?

I'd just like to do some code reviews first, to make sure I'm leaving it in good hands.

Do you also mind answering the same questions I asked in #69?

Thanks!

**Comment by edward-shen** [comment]
See #75 for more context.
