### ISSUE TITLE
MMM-Pages not working with MMM-Weather-Now and MMM-3Day-Forecast

### ISSUE THREAD

**Issue by JanVelleman** [edward-shen/MMM-pages#8]
*Describe the bug**
I have 5 pages and they work OK, I want to exclude: "MMM-Weather-Now" and "MMM-3Day-Forecast" but as soon as I activate the MMM-Pages module these 2 dissapear even if I add them to the exclude list.

I checked that they work before making the MMM-pages module active.

**To Reproduce**
just add these 2 modules to a config file where the pages module is avµctive an you cannot get them to show.

**Expected behavior**
They should appear as if they do without the pages module active.

**Screenshots**
If applicable, add screenshots to help explain your problem. If you believe you have aptly described your issue in words, feel free to ignore this section.

**Please fill out the following information;**
 - Node version: V9.11.2
 - Have you updated to the latest MagicMirror core? [yes]
 - Please post the relevant part of your config file here:
```json
modules: [
		 {
		        module: "MMM-pages",
		        config: {
		                modules:
		                    [[ "compliments", ],
				     [ "newsfeed" ],
				     [ "DailyXKCD" ],
				     [ "MMM-DailyDilbert" ],
		                     [ "MMM-quote-of-the-day" ]],
		                excludes: ["clock","MMM-OnScreenMenu", "MMM-Weather-Now", "MMM-3Day-Forecast", "MMM-page-indicator"],
				animationTime: 2000,
				rotationTime: 20000,
				delayTime: 200000
		    	}
                },
		{
		        module: "MMM-page-indicator",
		        position: 'bottom_bar',
		        config: {
		            pages: 5,
		        }
    		},
		{
			module: "clock",
			position: "top_left",
			config: {
				timeFormat: 24,
				displaySeconds: true,
				displayType: "both",
				timezone: "Etc/GMT-2"
			}
		},
		{
	            	module: "MMM-OnScreenMenu",
	            	position: "bottom_left",
	            	config: {
	                	touchMode: false,
	                	enableKeyboard: true
	            	}
    		},
		{
			module: "MMM-Weather-Now",
			position: "top_left",
			config: {
				api_key:    "xxxxxxxxxxxxxxxx",
				lat:	    51.054342,
				lon:	    3.717424,
				units:	    "M",
				lang:	    "en",
				interval:   900000
			}
		},
... and so on
```
 - Please post any errors you see about MMM-Pages in the console (Hit F12 > Console when the Magic Mirror window is focused), or write **None** if there aren't any:
```
```
**Additional context**
I think somehow the opacity of these modules is staying at 0?

**Comment by edward-shen** [comment]
Thanks for filing a bug report!

Just to let you know, I've edited and deleted the version of your post that contains the API key. These keys should be kept private at all times!

Also, could you please post the part of the config that contains MMM-3Day-Forecast's config as well?

**Comment by JanVelleman** [comment]
Hi,

Thanks fot the fast reply.
Thx for removing the key, forgot about that one. 

For the 3day forecast module the config is exactly the same as the Weather Now one (made by same guy). 

I do not have acces to my mirror system at the moment but i will post the complete config when i do (probably monday)

Sincerely

**Comment by JanVelleman** [comment]
See the config of both modules below:

`{
			module: "MMM-Weather-Now",
			position: "top_left",
			config: {
				api_key:    "eeed7cb2c408483898e9de98e5c9e77f",
				lat:	    51.054342,
				lon:	    3.717424,
				units:	    "M",
				lang:	    "en",
				interval:   900000
			}
		},
		{
		    	module: "MMM-3Day-Forecast",
		    	position: "top_left",
			config: {
				api_key:    "eeed7cb2c408483898e9de98e5c9e77f",
				lat:        51.054342,
				lon:	    3.717424,
				units:      "M",
				lang:       "en",
				interval:   900000
				}
		},`

**Comment by edward-shen** [comment]
I have figured out the issue and deemed it to be breaking behavior to be an issue in the other modules. I have made a PR request to both modules that you reported breaking behavior in. It is up to them to resolve the issue.

In the meantime, you may use my fork instead (which resolves the issue) until they accepts my fix.

**Comment by edward-shen** [comment]
Just to give you an update, the creator of the MagicMirror platform has confirmed that this is an issue on the other modules' end. The developer of those modules should be making a fix shortly.

**Comment by JanVelleman** [comment]
Hi,

Thanks for the fast replies (was on a holiday past 2 days) Thanks for the solution :)

**Comment by edward-shen** [comment]
Final update, the developer of the modules have updated the modules to fix your issue. You should no longer have that issue!

**Comment by JanVelleman** [comment]
thx!
