### ISSUE TITLE
Using MMM-Buttons to increment and decrement makes MMM-Pages send a whole lot of increment notifications by itself

### ISSUE THREAD

**Issue by JanVelleman** [edward-shen/MMM-pages#9]
**Describe the bug**
I'm using MMM-Buttons to send an increment or decrement page notification, wich works. But after the rotationtime the MMM-Pages module starts to generate increment notifications by itself (checked in console). Seemingly random. The buttons keep working during this. 

When not using the MMM-Buttons module this behavior is not present.

I am also using your Page indicator module

**To Reproduce**
use the MMM-Buttons module to send increment and decrement notifications to the MMM-Pages module and wait until the rotationtime has elapsed.

**Expected behavior**
MMM-Pages should not generate increment notifications by itself

**Comment by JanVelleman** [comment]
I have made a small video about the problem, first you see me restarrting the magic mirror software, then decrementing the page count with a button (mirror responds fine) the rotationdelay is set at 20 seconds. When the 20 seconds pass the mirror starts to behave weird... When restarting the mirror auto rotate works fine again until I have manually change page number...

any ideas??

https://1drv.ms/v/s!AkB62gmPn-IZgsVPY2KcrYYYYvO2jg

**Comment by JanVelleman** [comment]
I'm not good enough in understanding your code but if I put rotationdelay at 0 then the random behaviour does not happen.

I expect the problem is in this piece of code (setinterval?)

``
updatePages: function (manuallyCalled) {

    if (this.config.modules.length !== 0) {

      // We need to use self because upstream uses an older electron and thus

      // older version of node

      const self = this;



      Log.log(`updatePages was ${manuallyCalled ? '' : 'not'} manually called`);



      // Hides the current page's elements.

      MM.getModules()

        .exceptWithClass(this.config.excludes)

        .exceptWithClass(this.config.modules[this.curPage])

        .enumerate((module) => {

          module.hide(

            self.config.animationTime / 2,

            { lockString: self.identifier }

          );

        });



      // Shows the next page's elements

      setTimeout(() => MM.getModules()

        .withClass(self.config.modules[self.curPage])

        .enumerate(module => module.show(

          self.config.animationTime / 2,

          { lockString: self.identifier },

        )), this.config.animationTime / 2);



      if (manuallyCalled && this.config.rotationTime > 0) {

        Log.log('Manually updated page! setting delay before resuming timer!');



        clearInterval(this.timer);



        setTimeout(() => {

          self.timer = setInterval(() => {

            // Incrementing page

            self.curPage = self.mod(

              self.curPage + 1,

              self.config.modules.length

            );

            self.sendNotification('PAGE_INCREMENT');

            self.updatePages(false);

          }, self.config.rotationTime, false);

        }, this.config.rotationDelay);

      }

    } else { Log.error("Pages aren't properly defined!"); }

  },

});

``

**Comment by edward-shen** [comment]
Thanks for the video! I'm current out on a business trip and will be back Wednesday, so I won't be able to work on it until then.

**Comment by JanVelleman** [comment]
Hi, did you already have some time to look at this problem?

Sincerely

**Comment by edward-shen** [comment]
Hello,
I'm still working on the module, but I'm starting to figure out what's going on! This module's a little more complex, and so removing rotationDelay might break other features.

Could you also please post your configs as well? Any more information helps!

**Comment by edward-shen** [comment]
Try updating. I think I fixed the issue you were describing.

**Comment by edward-shen** [comment]
If it doesn't work, reopen this issue and I'll happily try and work on it more!

**Comment by JanVelleman** [comment]
Hi Edward,

The problem seems to be solved indeed, Thanks!
However, I also use your page indicator plugin, which previously worked fine but after your update of the pages plugin it no longer updates on an automatic page increment. When I give a notifications it still changes but it doesn't when the page changes when the rotation delay rolls over?


I tried updating the indicator plugin, thinking you also updated it but it says it's already up to date.

**Comment by edward-shen** [comment]
Whoops! I forgot to send a notification when rotating again. This should be fixed now! Sorry!

Try again, let me know if it's fixed!

**Comment by JanVelleman** [comment]
Works fine now :) Thx

**Comment by JanVelleman** [comment]
Hi, maybe unrelated but since your update I get a weird white/gray screen if I leave the mirror on for some time. I did not do anything else beside update you module. If I touch the keyboard or mouse it reurns to normal. Any idea?
![20180828_092932875_ios](https://user-images.githubusercontent.com/10757423/44715392-ff136b80-aab7-11e8-9cea-5f9e6d729b75.jpg)
![20180828_092946200_ios](https://user-images.githubusercontent.com/10757423/44715393-ff136b80-aab7-11e8-9848-16f03164e6d5.jpg)

**Comment by edward-shen** [comment]
Wow, that's a pretty crazy issue.

Try removing my modules and see if the issue continues (e.g. commenting out the config).

I don't think this is related to MMM-pages tho, especially since it disappears after you move the mouse or use the keyboard. That sounds like an issue with the device bugging out after it tries to go to sleep.
